#include "BlockDataRegistry.h"
#include "InverseMap.h"

namespace Minecraft::Server::Internal::Registry {
    BlockDataRegistry::BlockDataRegistry()
    {
        registryMap.clear();
    }

    BlockDataRegistry::~BlockDataRegistry()
    {

    }

	void BlockDataRegistry::registerVanillaBlockData() {

		BlockData* terracotta = new BlockData();
		terracotta->snowable = false;
		terracotta->blockHeight = 1.0f;
		terracotta->blocksRain = true;
		terracotta->fullBlock = true;
		terracotta->hardness = 1.4f;
		terracotta->lightValue = 0.0f;
		terracotta->oneHitDig = false;
		terracotta->pistonBreak = false;
		terracotta->skylightDispersant = false;
		terracotta->solid = true;
		terracotta->spreadLightFalloff = 15.0f; //Opaque
		terracotta->transparent = false;

		BlockData* log = new BlockData();
		log->snowable = false;
		log->blockHeight = 1.0f;
		log->blocksRain = true;
		log->fullBlock = true;
		log->hardness = 2.0f;
		log->lightValue = 0.0f;
		log->oneHitDig = false;
		log->pistonBreak = false;
		log->skylightDispersant = false;
		log->solid = true;
		log->spreadLightFalloff = 15.0f; //Opaque
		log->transparent = false;

		BlockData* bricks = new BlockData();
		log->snowable = false;
		log->blockHeight = 1.0f;
		log->blocksRain = true;
		log->fullBlock = true;
		log->hardness = 1.5f;
		log->lightValue = 0.0f;
		log->oneHitDig = false;
		log->pistonBreak = false;
		log->skylightDispersant = false;
		log->solid = true;
		log->spreadLightFalloff = 15.0f; //Opaque
		log->transparent = false;

		BlockData* planks = new BlockData();
		planks->snowable = false;
		planks->blockHeight = 1.0f;
		planks->blocksRain = true;
		planks->fullBlock = true;
		planks->hardness = 2.0f;
		planks->lightValue = 0.0f;
		planks->oneHitDig = false;
		planks->pistonBreak = false;
		planks->skylightDispersant = false;
		planks->solid = true;
		planks->spreadLightFalloff = 15.0f; //Opaque
		planks->transparent = false;

		BlockData* coral_block = new BlockData();
		coral_block->snowable = false;
		coral_block->blockHeight = 1.0f;
		coral_block->blocksRain = true;
		coral_block->fullBlock = true;
		coral_block->hardness = 1.5f;
		coral_block->lightValue = 0.0f;
		coral_block->oneHitDig = false;
		coral_block->pistonBreak = false;
		coral_block->skylightDispersant = false;
		coral_block->solid = true;
		coral_block->spreadLightFalloff = 15.0f; //Opaque
		coral_block->transparent = false;

		BlockData* ore = new BlockData();
		ore->snowable = false;
		ore->blockHeight = 1.0f;
		ore->blocksRain = true;
		ore->fullBlock = true;
		ore->hardness = 3.0f;
		ore->lightValue = 0.0f;
		ore->oneHitDig = false;
		ore->pistonBreak = false;
		ore->skylightDispersant = false;
		ore->solid = true;
		ore->spreadLightFalloff = 15.0f; //Opaque
		ore->transparent = false;

		BlockData* concrete = new BlockData();
		concrete->snowable = false;
		concrete->blockHeight = 1.0f;
		concrete->blocksRain = true;
		concrete->fullBlock = true;
		concrete->hardness = 1.8f;
		concrete->lightValue = 0.0f;
		concrete->oneHitDig = false;
		concrete->pistonBreak = false;
		concrete->skylightDispersant = false;
		concrete->solid = true;
		concrete->spreadLightFalloff = 15.0f; //Opaque
		concrete->transparent = false;

		BlockData* sandstone = new BlockData();
		sandstone->snowable = false;
		sandstone->blockHeight = 1.0f;
		sandstone->blocksRain = true;
		sandstone->fullBlock = true;
		sandstone->hardness = 0.8f;
		sandstone->lightValue = 0.0f;
		sandstone->oneHitDig = false;
		sandstone->pistonBreak = false;
		sandstone->skylightDispersant = false;
		sandstone->solid = true;
		sandstone->spreadLightFalloff = 15.0f; //Opaque
		sandstone->transparent = false;

		BlockData* concrete_powder = new BlockData();
		concrete_powder->snowable = false;
		concrete_powder->blockHeight = 1.0f;
		concrete_powder->blocksRain = true;
		concrete_powder->fullBlock = true;
		concrete_powder->hardness = 0.5f;
		concrete_powder->lightValue = 0.0f;
		concrete_powder->oneHitDig = false;
		concrete_powder->pistonBreak = false;
		concrete_powder->skylightDispersant = false;
		concrete_powder->solid = true;
		concrete_powder->spreadLightFalloff = 15.0f; //Opaque
		concrete_powder->transparent = false;

		BlockData* shulker = new BlockData();
		shulker->snowable = false;
		shulker->blockHeight = 1.0f;
		shulker->blocksRain = true;
		shulker->fullBlock = true;
		shulker->hardness = 0.2f;
		shulker->lightValue = 0.0f;
		shulker->oneHitDig = false;
		shulker->pistonBreak = true;
		shulker->skylightDispersant = false;
		shulker->solid = true;
		shulker->spreadLightFalloff = 15.0f; //Opaque
		shulker->transparent = true;

		BlockData* wool = new BlockData();
		wool->snowable = false;
		wool->blockHeight = 1.0f;
		wool->blocksRain = true;
		wool->fullBlock = true;
		wool->hardness = 0.8f;
		wool->lightValue = 0.0f;
		wool->oneHitDig = false;
		wool->pistonBreak = false;
		wool->skylightDispersant = false;
		wool->solid = true;
		wool->spreadLightFalloff = 15.0f; //Opaque
		wool->transparent = false;

		BlockData* banner = new BlockData();
		banner->snowable = false;
		banner->blockHeight = 1.0f;
		banner->blocksRain = true;
		banner->fullBlock = false;
		banner->hardness = 1.0f;
		banner->lightValue = 0.0f;
		banner->oneHitDig = false;
		banner->pistonBreak = true;
		banner->skylightDispersant = false;
		banner->solid = true;
		banner->spreadLightFalloff = 1.0f; //Transparent
		banner->transparent = true;

		BlockData* bed = new BlockData();
		bed->snowable = false;
		bed->blockHeight = 0.5625f;
		bed->blocksRain = true;
		bed->fullBlock = false;
		bed->hardness = 0.2f;
		bed->lightValue = 0.0f;
		bed->oneHitDig = false;
		bed->pistonBreak = true;
		bed->skylightDispersant = false;
		bed->solid = true;
		bed->spreadLightFalloff = 1.0f; //Transparent
		bed->transparent = true;

		BlockData* glass = new BlockData();
		glass->snowable = false;
		glass->blockHeight = 1.0f;
		glass->blocksRain = true;
		glass->fullBlock = true;
		glass->hardness = 0.3f;
		glass->lightValue = 0.0f;
		glass->oneHitDig = false;
		glass->pistonBreak = false;
		glass->skylightDispersant = false;
		glass->solid = true;
		glass->spreadLightFalloff = 1.0f; //Transparent
		glass->transparent = true;

		BlockData* door = new BlockData();
		door->snowable = false;
		door->blockHeight = 1.0f;
		door->blocksRain = false;
		door->fullBlock = false;
		door->hardness = 3.0f;
		door->lightValue = 0.0f;
		door->oneHitDig = false;
		door->pistonBreak = true;
		door->skylightDispersant = false;
		door->solid = true;
		door->spreadLightFalloff = 1.0f; //Transparent
		door->transparent = true;

		BlockData* trapdoor = new BlockData();
		trapdoor->snowable = false;
		trapdoor->blockHeight = 1.0f;
		trapdoor->blocksRain = false;
		trapdoor->fullBlock = false;
		trapdoor->hardness = 3.0f;
		trapdoor->lightValue = 0.0f;
		trapdoor->oneHitDig = false;
		trapdoor->pistonBreak = true;
		trapdoor->skylightDispersant = false;
		trapdoor->solid = true;
		trapdoor->spreadLightFalloff = 1.0f; //Transparent
		trapdoor->transparent = true;

		BlockData* iron_door = new BlockData();
		door->snowable = false;
		door->blockHeight = 1.0f;
		door->blocksRain = false;
		door->fullBlock = false;
		door->hardness = 5.0f;
		door->lightValue = 0.0f;
		door->oneHitDig = false;
		door->pistonBreak = true;
		door->skylightDispersant = false;
		door->solid = true;
		door->spreadLightFalloff = 1.0f; //Transparent
		door->transparent = true;

		BlockData* iron_trapdoor = new BlockData();
		iron_trapdoor->snowable = false;
		iron_trapdoor->blockHeight = 1.0f;
		iron_trapdoor->blocksRain = false;
		iron_trapdoor->fullBlock = false;
		iron_trapdoor->hardness = 5.0f;
		iron_trapdoor->lightValue = 0.0f;
		iron_trapdoor->oneHitDig = false;
		iron_trapdoor->pistonBreak = true;
		iron_trapdoor->skylightDispersant = false;
		iron_trapdoor->solid = true;
		iron_trapdoor->spreadLightFalloff = 1.0f; //Transparent
		iron_trapdoor->transparent = true;

		BlockData* leaves = new BlockData();
		leaves->snowable = false;
		leaves->blockHeight = 1.0f;
		leaves->blocksRain = true;
		leaves->fullBlock = true;
		leaves->hardness = 0.2f;
		leaves->lightValue = 0.0f;
		leaves->oneHitDig = false;
		leaves->pistonBreak = false;
		leaves->skylightDispersant = false;
		leaves->solid = true;
		leaves->spreadLightFalloff = 1.0f; //Transparent
		leaves->transparent = true;

		BlockData* sapling = new BlockData();
		sapling->snowable = false;
		sapling->blockHeight = 1.0f;
		sapling->blocksRain = false;
		sapling->fullBlock = false;
		sapling->hardness = 0.0f;
		sapling->lightValue = 0.0f;
		sapling->oneHitDig = true;
		sapling->pistonBreak = false;
		sapling->skylightDispersant = false;
		sapling->solid = false;
		sapling->spreadLightFalloff = 1.0f; //Transparent
		sapling->transparent = true;

		BlockData* fence = new BlockData();
		fence->snowable = false;
		fence->blockHeight = 1.5f;
		fence->blocksRain = true;
		fence->fullBlock = false;
		fence->hardness = 2.0f;
		fence->lightValue = 0.0f;
		fence->oneHitDig = false;
		fence->pistonBreak = false;
		fence->skylightDispersant = false;
		fence->solid = true;
		fence->spreadLightFalloff = 1.0f; //Transparent
		fence->transparent = true;

		BlockData* carpet = new BlockData();
		carpet->snowable = false;
		carpet->blockHeight = 0.0625f;
		carpet->blocksRain = true;
		carpet->fullBlock = false;
		carpet->hardness = 0.1f;
		carpet->lightValue = 0.0f;
		carpet->oneHitDig = false;
		carpet->pistonBreak = true;
		carpet->skylightDispersant = false;
		carpet->solid = false;
		carpet->spreadLightFalloff = 1.0f; //Transparent
		carpet->transparent = true;

		BlockData* rail = new BlockData();
		rail->snowable = false;
		rail->blockHeight = 0.0625f;
		rail->blocksRain = true;
		rail->fullBlock = false;
		rail->hardness = 0.7f;
		rail->lightValue = 0.0f;
		rail->oneHitDig = false;
		rail->pistonBreak = true;
		rail->skylightDispersant = false;
		rail->solid = false;
		rail->spreadLightFalloff = 1.0f; //Transparent
		rail->transparent = true;

		BlockData* slab = new BlockData();
		slab->snowable = false;
		slab->blockHeight = 0.5f;
		slab->blocksRain = true;
		slab->fullBlock = false;
		slab->hardness = 2.0f;
		slab->lightValue = 0.0f;
		slab->oneHitDig = false;
		slab->pistonBreak = false;
		slab->skylightDispersant = false;
		slab->solid = false;
		slab->spreadLightFalloff = 1.0f; //Transparent
		slab->transparent = true;

		BlockData* pressure_plate = new BlockData();
		pressure_plate->snowable = false;
		pressure_plate->blockHeight = 0.0625f;
		pressure_plate->blocksRain = true;
		pressure_plate->fullBlock = false;
		pressure_plate->hardness = 0.5f;
		pressure_plate->lightValue = 0.0f;
		pressure_plate->oneHitDig = false;
		pressure_plate->pistonBreak = true;
		pressure_plate->skylightDispersant = false;
		pressure_plate->solid = false;
		pressure_plate->spreadLightFalloff = 1.0f; //Transparent
		pressure_plate->transparent = true;

		BlockData* button = new BlockData();
		button->snowable = false;
		button->blockHeight = 0.04f;
		button->blocksRain = false;
		button->fullBlock = false;
		button->hardness = 0.5f;
		button->lightValue = 0.0f;
		button->oneHitDig = false;
		button->pistonBreak = true;
		button->skylightDispersant = false;
		button->solid = false;
		button->spreadLightFalloff = 1.0f; //Transparent
		button->transparent = true;

		BlockData* head = new BlockData();
		head->snowable = false;
		head->blockHeight = 0.04f;
		head->blocksRain = false;
		head->fullBlock = false;
		head->hardness = 1.0f;
		head->lightValue = 0.0f;
		head->oneHitDig = false;
		head->pistonBreak = true;
		head->skylightDispersant = false;
		head->solid = false;
		head->spreadLightFalloff = 1.0f; //Transparent
		head->transparent = true;

		BlockData* plant = new BlockData();
		plant->snowable = false;
		plant->blockHeight = 0.04f;
		plant->blocksRain = false;
		plant->fullBlock = false;
		plant->hardness = 0.0f;
		plant->lightValue = 0.0f;
		plant->oneHitDig = true;
		plant->pistonBreak = true;
		plant->skylightDispersant = false;
		plant->solid = false;
		plant->spreadLightFalloff = 1.0f; //Transparent
		plant->transparent = true;

		





		registryMap.emplace("minecraft:acacia_button", button);
		registryMap.emplace("minecraft:acacia_door", door);
		registryMap.emplace("minecraft:acacia_fence", fence);
		registryMap.emplace("minecraft:acacia_fence_gate", fence);
		registryMap.emplace("minecraft:acacia_leaves", leaves);
		registryMap.emplace("minecraft:acacia_log", log);
		registryMap.emplace("minecraft:acacia_planks", planks);
		registryMap.emplace("minecraft:acacia_pressure_plate", pressure_plate);
		registryMap.emplace("minecraft:acacia_sapling", sapling);
		registryMap.emplace("minecraft:acacia_slab", slab);
		registryMap.emplace("minecraft:acacia_stairs", new BlockData());
		registryMap.emplace("minecraft:acacia_trapdoor", trapdoor);
		registryMap.emplace("minecraft:acacia_wood", log);
		registryMap.emplace("minecraft:activator_rail", rail);
		registryMap.emplace("minecraft:air", new BlockData());
		registryMap.emplace("minecraft:allium", plant);
		registryMap.emplace("minecraft:andesite", new BlockData());
		registryMap.emplace("minecraft:anvil", new BlockData());
		registryMap.emplace("minecraft:attached_melon_stem", plant);
		registryMap.emplace("minecraft:attached_pumpkin_stem", plant);
		registryMap.emplace("minecraft:azure_bluet", plant);
		registryMap.emplace("minecraft:barrier", new BlockData());
		registryMap.emplace("minecraft:beacon", new BlockData());
		registryMap.emplace("minecraft:bedrock", new BlockData());
		registryMap.emplace("minecraft:beetroots", plant);
		registryMap.emplace("minecraft:birch_button", button);
		registryMap.emplace("minecraft:birch_door", door);
		registryMap.emplace("minecraft:birch_fence", fence);
		registryMap.emplace("minecraft:birch_fence_gate", fence);
		registryMap.emplace("minecraft:birch_leaves", leaves);
		registryMap.emplace("minecraft:birch_log", log);
		registryMap.emplace("minecraft:birch_planks", planks);
		registryMap.emplace("minecraft:birch_pressure_plate", pressure_plate);
		registryMap.emplace("minecraft:birch_sapling", sapling);
		registryMap.emplace("minecraft:birch_slab", slab);
		registryMap.emplace("minecraft:birch_stairs", new BlockData());
		registryMap.emplace("minecraft:birch_trapdoor", trapdoor);
		registryMap.emplace("minecraft:birch_wood", log);
		registryMap.emplace("minecraft:black_banner", banner);
		registryMap.emplace("minecraft:black_bed", bed);
		registryMap.emplace("minecraft:black_carpet", carpet);
		registryMap.emplace("minecraft:black_concrete", concrete);
		registryMap.emplace("minecraft:black_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:black_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:black_shulker_box", shulker);
		registryMap.emplace("minecraft:black_stained_glass", glass);
		registryMap.emplace("minecraft:black_stained_glass_pane", glass);
		registryMap.emplace("minecraft:black_terracotta", terracotta);
		registryMap.emplace("minecraft:black_wall_banner", banner);
		registryMap.emplace("minecraft:black_wool", wool);
		registryMap.emplace("minecraft:blue_banner", banner);
		registryMap.emplace("minecraft:blue_bed", bed);
		registryMap.emplace("minecraft:blue_carpet", carpet);
		registryMap.emplace("minecraft:blue_concrete", concrete);
		registryMap.emplace("minecraft:blue_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:blue_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:blue_ice", new BlockData());
		registryMap.emplace("minecraft:blue_orchid", plant);
		registryMap.emplace("minecraft:blue_shulker_box", shulker);
		registryMap.emplace("minecraft:blue_stained_glass", glass);
		registryMap.emplace("minecraft:blue_stained_glass_pane", glass);
		registryMap.emplace("minecraft:blue_terracotta", terracotta);
		registryMap.emplace("minecraft:blue_wall_banner", banner);
		registryMap.emplace("minecraft:blue_wool", wool);
		registryMap.emplace("minecraft:bone_block", new BlockData());
		registryMap.emplace("minecraft:bookshelf", new BlockData());
		registryMap.emplace("minecraft:brain_coral", plant);
		registryMap.emplace("minecraft:brain_coral_block", coral_block);
		registryMap.emplace("minecraft:brain_coral_fan", plant);
		registryMap.emplace("minecraft:brain_coral_wall_fan", plant);
		registryMap.emplace("minecraft:brewing_stand", new BlockData());
		registryMap.emplace("minecraft:brick_slab", slab);
		registryMap.emplace("minecraft:brick_stairs", new BlockData());
		registryMap.emplace("minecraft:bricks", bricks);
		registryMap.emplace("minecraft:brown_banner", banner);
		registryMap.emplace("minecraft:brown_bed", bed);
		registryMap.emplace("minecraft:brown_carpet", carpet);
		registryMap.emplace("minecraft:brown_concrete", concrete);
		registryMap.emplace("minecraft:brown_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:brown_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:brown_mushroom", plant);
		registryMap.emplace("minecraft:brown_mushroom_block", new BlockData());
		registryMap.emplace("minecraft:brown_shulker_box", shulker);
		registryMap.emplace("minecraft:brown_stained_glass", glass);
		registryMap.emplace("minecraft:brown_stained_glass_pane", glass);
		registryMap.emplace("minecraft:brown_terracotta", terracotta);
		registryMap.emplace("minecraft:brown_wall_banner", banner);
		registryMap.emplace("minecraft:brown_wool", wool);
		registryMap.emplace("minecraft:bubble_column", new BlockData());
		registryMap.emplace("minecraft:bubble_coral", plant);
		registryMap.emplace("minecraft:bubble_coral_block", coral_block);
		registryMap.emplace("minecraft:bubble_coral_fan", plant);
		registryMap.emplace("minecraft:bubble_coral_wall_fan", plant);
		registryMap.emplace("minecraft:cactus", new BlockData());
		registryMap.emplace("minecraft:cake", new BlockData());
		registryMap.emplace("minecraft:carrots", plant);
		registryMap.emplace("minecraft:carved_pumpkin", new BlockData());
		registryMap.emplace("minecraft:cauldron", new BlockData());
		registryMap.emplace("minecraft:cave_air", new BlockData());
		registryMap.emplace("minecraft:chain_command_block", new BlockData());
		registryMap.emplace("minecraft:chest", new BlockData());
		registryMap.emplace("minecraft:chipped_anvil", new BlockData());
		registryMap.emplace("minecraft:chiseled_quartz_block", new BlockData());
		registryMap.emplace("minecraft:chiseled_red_sandstone", sandstone);
		registryMap.emplace("minecraft:chiseled_sandstone", sandstone);
		registryMap.emplace("minecraft:chiseled_stone_bricks", bricks);
		registryMap.emplace("minecraft:chorus_flower", new BlockData());
		registryMap.emplace("minecraft:chorus_plant", new BlockData());
		registryMap.emplace("minecraft:clay", new BlockData());
		registryMap.emplace("minecraft:coal_block", new BlockData());
		registryMap.emplace("minecraft:coal_ore", ore);
		registryMap.emplace("minecraft:coarse_dirt", new BlockData());
		registryMap.emplace("minecraft:cobblestone", new BlockData());
		registryMap.emplace("minecraft:cobblestone_slab", slab);
		registryMap.emplace("minecraft:cobblestone_stairs", new BlockData());
		registryMap.emplace("minecraft:cobblestone_wall", new BlockData());
		registryMap.emplace("minecraft:cobweb", new BlockData());
		registryMap.emplace("minecraft:cocoa", plant);
		registryMap.emplace("minecraft:command_block", new BlockData());
		registryMap.emplace("minecraft:comparator", new BlockData());
		registryMap.emplace("minecraft:conduit", new BlockData());
		registryMap.emplace("minecraft:cracked_stone_bricks", bricks);
		registryMap.emplace("minecraft:crafting_table", new BlockData());
		registryMap.emplace("minecraft:creeper_head", head);
		registryMap.emplace("minecraft:creeper_wall_head", head);
		registryMap.emplace("minecraft:cut_red_sandstone", sandstone);
		registryMap.emplace("minecraft:cut_sandstone", sandstone);
		registryMap.emplace("minecraft:cyan_banner", banner);
		registryMap.emplace("minecraft:cyan_bed", bed);
		registryMap.emplace("minecraft:cyan_carpet", carpet);
		registryMap.emplace("minecraft:cyan_concrete", concrete);
		registryMap.emplace("minecraft:cyan_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:cyan_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:cyan_shulker_box", shulker);
		registryMap.emplace("minecraft:cyan_stained_glass", glass);
		registryMap.emplace("minecraft:cyan_stained_glass_pane", glass);
		registryMap.emplace("minecraft:cyan_terracotta", terracotta);
		registryMap.emplace("minecraft:cyan_wall_banner", banner);
		registryMap.emplace("minecraft:cyan_wool", wool);
		registryMap.emplace("minecraft:damaged_anvil", new BlockData());
		registryMap.emplace("minecraft:dandelion", plant);
		registryMap.emplace("minecraft:dark_oak_button", button);
		registryMap.emplace("minecraft:dark_oak_door", door);
		registryMap.emplace("minecraft:dark_oak_fence", fence);
		registryMap.emplace("minecraft:dark_oak_fence_gate", fence);
		registryMap.emplace("minecraft:dark_oak_leaves", leaves);
		registryMap.emplace("minecraft:dark_oak_log", log);
		registryMap.emplace("minecraft:dark_oak_planks", planks);
		registryMap.emplace("minecraft:dark_oak_pressure_plate", pressure_plate);
		registryMap.emplace("minecraft:dark_oak_sapling", sapling);
		registryMap.emplace("minecraft:dark_oak_slab", slab);
		registryMap.emplace("minecraft:dark_oak_stairs", new BlockData());
		registryMap.emplace("minecraft:dark_oak_trapdoor", trapdoor);
		registryMap.emplace("minecraft:dark_oak_wood", log);
		registryMap.emplace("minecraft:dark_prismarine", new BlockData());
		registryMap.emplace("minecraft:dark_prismarine_slab", slab);
		registryMap.emplace("minecraft:dark_prismarine_stairs", new BlockData());
		registryMap.emplace("minecraft:daylight_detector", new BlockData());
		registryMap.emplace("minecraft:dead_brain_coral", plant);
		registryMap.emplace("minecraft:dead_brain_coral_block", coral_block);
		registryMap.emplace("minecraft:dead_brain_coral_fan", plant);
		registryMap.emplace("minecraft:dead_brain_coral_wall_fan", plant);
		registryMap.emplace("minecraft:dead_bubble_coral", plant);
		registryMap.emplace("minecraft:dead_bubble_coral_block", coral_block);
		registryMap.emplace("minecraft:dead_bubble_coral_fan", plant);
		registryMap.emplace("minecraft:dead_bubble_coral_wall_fan", plant);
		registryMap.emplace("minecraft:dead_bush", plant);
		registryMap.emplace("minecraft:dead_fire_coral", plant);
		registryMap.emplace("minecraft:dead_fire_coral_block", coral_block);
		registryMap.emplace("minecraft:dead_fire_coral_fan", plant);
		registryMap.emplace("minecraft:dead_fire_coral_wall_fan", plant);
		registryMap.emplace("minecraft:dead_horn_coral", plant);
		registryMap.emplace("minecraft:dead_horn_coral_block", coral_block);
		registryMap.emplace("minecraft:dead_horn_coral_fan", plant);
		registryMap.emplace("minecraft:dead_horn_coral_wall_fan", plant);
		registryMap.emplace("minecraft:dead_tube_coral", plant);
		registryMap.emplace("minecraft:dead_tube_coral_block", coral_block);
		registryMap.emplace("minecraft:dead_tube_coral_fan", plant);
		registryMap.emplace("minecraft:dead_tube_coral_wall_fan", plant);
		registryMap.emplace("minecraft:detector_rail", rail);
		registryMap.emplace("minecraft:diamond_block", new BlockData());
		registryMap.emplace("minecraft:diamond_ore", ore);
		registryMap.emplace("minecraft:diorite", new BlockData());
		registryMap.emplace("minecraft:dirt", new BlockData());
		registryMap.emplace("minecraft:dispenser", new BlockData());
		registryMap.emplace("minecraft:dragon_egg", new BlockData());
		registryMap.emplace("minecraft:dragon_head", head);
		registryMap.emplace("minecraft:dragon_wall_head", head);
		registryMap.emplace("minecraft:dried_kelp_block", new BlockData());
		registryMap.emplace("minecraft:dropper", new BlockData());
		registryMap.emplace("minecraft:emerald_block", new BlockData());
		registryMap.emplace("minecraft:emerald_ore", ore);
		registryMap.emplace("minecraft:enchanting_table", new BlockData());
		registryMap.emplace("minecraft:end_gateway", new BlockData());
		registryMap.emplace("minecraft:end_portal", new BlockData());
		registryMap.emplace("minecraft:end_portal_frame", new BlockData());
		registryMap.emplace("minecraft:end_rod", new BlockData());
		registryMap.emplace("minecraft:end_stone", new BlockData());
		registryMap.emplace("minecraft:end_stone_bricks", bricks);
		registryMap.emplace("minecraft:ender_chest", new BlockData());
		registryMap.emplace("minecraft:farmland", new BlockData());
		registryMap.emplace("minecraft:fern", plant);
		registryMap.emplace("minecraft:fire", new BlockData());
		registryMap.emplace("minecraft:fire_coral", plant);
		registryMap.emplace("minecraft:fire_coral_block", coral_block);
		registryMap.emplace("minecraft:fire_coral_fan", plant);
		registryMap.emplace("minecraft:fire_coral_wall_fan", plant);
		registryMap.emplace("minecraft:flower_pot", new BlockData());
		registryMap.emplace("minecraft:frosted_ice", new BlockData());
		registryMap.emplace("minecraft:furnace", new BlockData());
		registryMap.emplace("minecraft:glass", glass);
		registryMap.emplace("minecraft:glass_pane", glass);
		registryMap.emplace("minecraft:glowstone", new BlockData());
		registryMap.emplace("minecraft:gold_block", new BlockData());
		registryMap.emplace("minecraft:gold_ore", ore);
		registryMap.emplace("minecraft:granite", new BlockData());
		registryMap.emplace("minecraft:grass", plant);
		registryMap.emplace("minecraft:grass_block", new BlockData());
		registryMap.emplace("minecraft:grass_path", new BlockData());
		registryMap.emplace("minecraft:gravel", new BlockData());
		registryMap.emplace("minecraft:gray_banner", banner);
		registryMap.emplace("minecraft:gray_bed", bed);
		registryMap.emplace("minecraft:gray_carpet", carpet);
		registryMap.emplace("minecraft:gray_concrete", concrete);
		registryMap.emplace("minecraft:gray_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:gray_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:gray_shulker_box", shulker);
		registryMap.emplace("minecraft:gray_stained_glass", glass);
		registryMap.emplace("minecraft:gray_stained_glass_pane", glass);
		registryMap.emplace("minecraft:gray_terracotta", terracotta);
		registryMap.emplace("minecraft:gray_wall_banner", banner);
		registryMap.emplace("minecraft:gray_wool", wool);
		registryMap.emplace("minecraft:green_banner", banner);
		registryMap.emplace("minecraft:green_bed", bed);
		registryMap.emplace("minecraft:green_carpet", carpet);
		registryMap.emplace("minecraft:green_concrete", concrete);
		registryMap.emplace("minecraft:green_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:green_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:green_shulker_box", shulker);
		registryMap.emplace("minecraft:green_stained_glass", glass);
		registryMap.emplace("minecraft:green_stained_glass_pane", glass);
		registryMap.emplace("minecraft:green_terracotta", terracotta);
		registryMap.emplace("minecraft:green_wall_banner", banner);
		registryMap.emplace("minecraft:green_wool", wool);
		registryMap.emplace("minecraft:hay_block", new BlockData());
		registryMap.emplace("minecraft:heavy_weighted_pressure_plate", pressure_plate);
		registryMap.emplace("minecraft:hopper", new BlockData());
		registryMap.emplace("minecraft:horn_coral", plant);
		registryMap.emplace("minecraft:horn_coral_block", coral_block);
		registryMap.emplace("minecraft:horn_coral_fan", plant);
		registryMap.emplace("minecraft:horn_coral_wall_fan", plant);
		registryMap.emplace("minecraft:ice", new BlockData());
		registryMap.emplace("minecraft:infested_chiseled_stone_bricks", bricks);
		registryMap.emplace("minecraft:infested_cobblestone", new BlockData());
		registryMap.emplace("minecraft:infested_cracked_stone_bricks", bricks);
		registryMap.emplace("minecraft:infested_mossy_stone_bricks", bricks);
		registryMap.emplace("minecraft:infested_stone", new BlockData());
		registryMap.emplace("minecraft:infested_stone_bricks", bricks);
		registryMap.emplace("minecraft:iron_bars", new BlockData());
		registryMap.emplace("minecraft:iron_block", new BlockData());
		registryMap.emplace("minecraft:iron_door", iron_door);
		registryMap.emplace("minecraft:iron_ore", ore);
		registryMap.emplace("minecraft:iron_trapdoor", iron_trapdoor);
		registryMap.emplace("minecraft:jack_o_lantern", new BlockData());
		registryMap.emplace("minecraft:jukebox", new BlockData());
		registryMap.emplace("minecraft:jungle_button", button);
		registryMap.emplace("minecraft:jungle_door", door);
		registryMap.emplace("minecraft:jungle_fence", fence);
		registryMap.emplace("minecraft:jungle_fence_gate", fence);
		registryMap.emplace("minecraft:jungle_leaves", leaves);
		registryMap.emplace("minecraft:jungle_log", log);
		registryMap.emplace("minecraft:jungle_planks", planks);
		registryMap.emplace("minecraft:jungle_pressure_plate", pressure_plate);
		registryMap.emplace("minecraft:jungle_sapling", sapling);
		registryMap.emplace("minecraft:jungle_slab", slab);
		registryMap.emplace("minecraft:jungle_stairs", new BlockData());
		registryMap.emplace("minecraft:jungle_trapdoor", trapdoor);
		registryMap.emplace("minecraft:jungle_wood", log);
		registryMap.emplace("minecraft:kelp", plant);
		registryMap.emplace("minecraft:kelp_plant", plant);
		registryMap.emplace("minecraft:ladder", new BlockData());
		registryMap.emplace("minecraft:lapis_block", new BlockData());
		registryMap.emplace("minecraft:lapis_ore", ore);
		registryMap.emplace("minecraft:large_fern", plant);
		registryMap.emplace("minecraft:lava", new BlockData());
		registryMap.emplace("minecraft:lever", new BlockData());
		registryMap.emplace("minecraft:light_blue_banner", banner);
		registryMap.emplace("minecraft:light_blue_bed", bed);
		registryMap.emplace("minecraft:light_blue_carpet", carpet);
		registryMap.emplace("minecraft:light_blue_concrete", concrete);
		registryMap.emplace("minecraft:light_blue_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:light_blue_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:light_blue_shulker_box", shulker);
		registryMap.emplace("minecraft:light_blue_stained_glass", glass);
		registryMap.emplace("minecraft:light_blue_stained_glass_pane", glass);
		registryMap.emplace("minecraft:light_blue_terracotta", terracotta);
		registryMap.emplace("minecraft:light_blue_wall_banner", banner);
		registryMap.emplace("minecraft:light_blue_wool", wool);
		registryMap.emplace("minecraft:light_gray_banner", banner);
		registryMap.emplace("minecraft:light_gray_bed", bed);
		registryMap.emplace("minecraft:light_gray_carpet", carpet);
		registryMap.emplace("minecraft:light_gray_concrete", concrete);
		registryMap.emplace("minecraft:light_gray_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:light_gray_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:light_gray_shulker_box", shulker);
		registryMap.emplace("minecraft:light_gray_stained_glass", glass);
		registryMap.emplace("minecraft:light_gray_stained_glass_pane", glass);
		registryMap.emplace("minecraft:light_gray_terracotta", terracotta);
		registryMap.emplace("minecraft:light_gray_wall_banner", banner);
		registryMap.emplace("minecraft:light_gray_wool", wool);
		registryMap.emplace("minecraft:light_weighted_pressure_plate", pressure_plate);
		registryMap.emplace("minecraft:lilac", plant);
		registryMap.emplace("minecraft:lily_pad", new BlockData());
		registryMap.emplace("minecraft:lime_banner", banner);
		registryMap.emplace("minecraft:lime_bed", bed);
		registryMap.emplace("minecraft:lime_carpet", carpet);
		registryMap.emplace("minecraft:lime_concrete", concrete);
		registryMap.emplace("minecraft:lime_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:lime_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:lime_shulker_box", shulker);
		registryMap.emplace("minecraft:lime_stained_glass", glass);
		registryMap.emplace("minecraft:lime_stained_glass_pane", glass);
		registryMap.emplace("minecraft:lime_terracotta", terracotta);
		registryMap.emplace("minecraft:lime_wall_banner", banner);
		registryMap.emplace("minecraft:lime_wool", wool);
		registryMap.emplace("minecraft:magenta_banner", banner);
		registryMap.emplace("minecraft:magenta_bed", bed);
		registryMap.emplace("minecraft:magenta_carpet", carpet);
		registryMap.emplace("minecraft:magenta_concrete", concrete);
		registryMap.emplace("minecraft:magenta_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:magenta_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:magenta_shulker_box", shulker);
		registryMap.emplace("minecraft:magenta_stained_glass", glass);
		registryMap.emplace("minecraft:magenta_stained_glass_pane", glass);
		registryMap.emplace("minecraft:magenta_terracotta", terracotta);
		registryMap.emplace("minecraft:magenta_wall_banner", banner);
		registryMap.emplace("minecraft:magenta_wool", wool);
		registryMap.emplace("minecraft:magma_block", new BlockData());
		registryMap.emplace("minecraft:melon", new BlockData());
		registryMap.emplace("minecraft:melon_stem", plant);
		registryMap.emplace("minecraft:mossy_cobblestone", new BlockData());
		registryMap.emplace("minecraft:mossy_cobblestone_wall", new BlockData());
		registryMap.emplace("minecraft:mossy_stone_bricks", bricks);
		registryMap.emplace("minecraft:moving_piston", new BlockData());
		registryMap.emplace("minecraft:mushroom_stem", new BlockData());
		registryMap.emplace("minecraft:mycelium", new BlockData());
		registryMap.emplace("minecraft:nether_brick_fence", fence);
		registryMap.emplace("minecraft:nether_brick_slab", slab);
		registryMap.emplace("minecraft:nether_brick_stairs", new BlockData());
		registryMap.emplace("minecraft:nether_bricks", bricks);
		registryMap.emplace("minecraft:nether_portal", new BlockData());
		registryMap.emplace("minecraft:nether_quartz_ore", ore);
		registryMap.emplace("minecraft:nether_wart", plant);
		registryMap.emplace("minecraft:nether_wart_block", new BlockData());
		registryMap.emplace("minecraft:netherrack", new BlockData());
		registryMap.emplace("minecraft:note_block", new BlockData());
		registryMap.emplace("minecraft:oak_button", button);
		registryMap.emplace("minecraft:oak_door", door);
		registryMap.emplace("minecraft:oak_fence", fence);
		registryMap.emplace("minecraft:oak_fence_gate", fence);
		registryMap.emplace("minecraft:oak_leaves", leaves);
		registryMap.emplace("minecraft:oak_log", log);
		registryMap.emplace("minecraft:oak_planks", planks);
		registryMap.emplace("minecraft:oak_pressure_plate", pressure_plate);
		registryMap.emplace("minecraft:oak_sapling", sapling);
		registryMap.emplace("minecraft:oak_slab", slab);
		registryMap.emplace("minecraft:oak_stairs", new BlockData());
		registryMap.emplace("minecraft:oak_trapdoor", trapdoor);
		registryMap.emplace("minecraft:oak_wood", log);
		registryMap.emplace("minecraft:observer", new BlockData());
		registryMap.emplace("minecraft:obsidian", new BlockData());
		registryMap.emplace("minecraft:orange_banner", banner);
		registryMap.emplace("minecraft:orange_bed", bed);
		registryMap.emplace("minecraft:orange_carpet", carpet);
		registryMap.emplace("minecraft:orange_concrete", concrete);
		registryMap.emplace("minecraft:orange_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:orange_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:orange_shulker_box", shulker);
		registryMap.emplace("minecraft:orange_stained_glass", glass);
		registryMap.emplace("minecraft:orange_stained_glass_pane", glass);
		registryMap.emplace("minecraft:orange_terracotta", terracotta);
		registryMap.emplace("minecraft:orange_tulip", plant);
		registryMap.emplace("minecraft:orange_wall_banner", banner);
		registryMap.emplace("minecraft:orange_wool", wool);
		registryMap.emplace("minecraft:oxeye_daisy", plant);
		registryMap.emplace("minecraft:packed_ice", new BlockData());
		registryMap.emplace("minecraft:peony", plant);
		registryMap.emplace("minecraft:petrified_oak_slab", slab);
		registryMap.emplace("minecraft:pink_banner", banner);
		registryMap.emplace("minecraft:pink_bed", bed);
		registryMap.emplace("minecraft:pink_carpet", carpet);
		registryMap.emplace("minecraft:pink_concrete", concrete);
		registryMap.emplace("minecraft:pink_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:pink_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:pink_shulker_box", shulker);
		registryMap.emplace("minecraft:pink_stained_glass", glass);
		registryMap.emplace("minecraft:pink_stained_glass_pane", glass);
		registryMap.emplace("minecraft:pink_terracotta", terracotta);
		registryMap.emplace("minecraft:pink_tulip", plant);
		registryMap.emplace("minecraft:pink_wall_banner", banner);
		registryMap.emplace("minecraft:pink_wool", wool);
		registryMap.emplace("minecraft:piston", new BlockData());
		registryMap.emplace("minecraft:piston_head", head);
		registryMap.emplace("minecraft:player_head", head);
		registryMap.emplace("minecraft:player_wall_head", head);
		registryMap.emplace("minecraft:podzol", new BlockData());
		registryMap.emplace("minecraft:polished_andesite", new BlockData());
		registryMap.emplace("minecraft:polished_diorite", new BlockData());
		registryMap.emplace("minecraft:polished_granite", new BlockData());
		registryMap.emplace("minecraft:poppy", plant);
		registryMap.emplace("minecraft:potatoes", new BlockData());
		registryMap.emplace("minecraft:potted_acacia_sapling", sapling);
		registryMap.emplace("minecraft:potted_allium", plant);
		registryMap.emplace("minecraft:potted_azure_bluet", plant);
		registryMap.emplace("minecraft:potted_birch_sapling", sapling);
		registryMap.emplace("minecraft:potted_blue_orchid", plant);
		registryMap.emplace("minecraft:potted_brown_mushroom", plant);
		registryMap.emplace("minecraft:potted_cactus", plant);
		registryMap.emplace("minecraft:potted_dandelion", plant);
		registryMap.emplace("minecraft:potted_dark_oak_sapling", sapling);
		registryMap.emplace("minecraft:potted_dead_bush", plant);
		registryMap.emplace("minecraft:potted_fern", plant);
		registryMap.emplace("minecraft:potted_jungle_sapling", sapling);
		registryMap.emplace("minecraft:potted_oak_sapling", sapling);
		registryMap.emplace("minecraft:potted_orange_tulip", plant);
		registryMap.emplace("minecraft:potted_oxeye_daisy", plant);
		registryMap.emplace("minecraft:potted_pink_tulip", plant);
		registryMap.emplace("minecraft:potted_poppy", plant);
		registryMap.emplace("minecraft:potted_red_mushroom", plant);
		registryMap.emplace("minecraft:potted_red_tulip", plant);
		registryMap.emplace("minecraft:potted_spruce_sapling", sapling);
		registryMap.emplace("minecraft:potted_white_tulip", plant);
		registryMap.emplace("minecraft:powered_rail", rail);
		registryMap.emplace("minecraft:prismarine", new BlockData());
		registryMap.emplace("minecraft:prismarine_brick_slab", slab);
		registryMap.emplace("minecraft:prismarine_brick_stairs", new BlockData());
		registryMap.emplace("minecraft:prismarine_bricks", bricks);
		registryMap.emplace("minecraft:prismarine_slab", slab);
		registryMap.emplace("minecraft:prismarine_stairs", new BlockData());
		registryMap.emplace("minecraft:pumpkin", new BlockData());
		registryMap.emplace("minecraft:pumpkin_stem", plant);
		registryMap.emplace("minecraft:purple_banner", banner);
		registryMap.emplace("minecraft:purple_bed", bed);
		registryMap.emplace("minecraft:purple_carpet", carpet);
		registryMap.emplace("minecraft:purple_concrete", concrete);
		registryMap.emplace("minecraft:purple_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:purple_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:purple_shulker_box", shulker);
		registryMap.emplace("minecraft:purple_stained_glass", glass);
		registryMap.emplace("minecraft:purple_stained_glass_pane", glass);
		registryMap.emplace("minecraft:purple_terracotta", terracotta);
		registryMap.emplace("minecraft:purple_wall_banner", banner);
		registryMap.emplace("minecraft:purple_wool", wool);
		registryMap.emplace("minecraft:purpur_block", new BlockData());
		registryMap.emplace("minecraft:purpur_pillar", new BlockData());
		registryMap.emplace("minecraft:purpur_slab", slab);
		registryMap.emplace("minecraft:purpur_stairs", new BlockData());
		registryMap.emplace("minecraft:quartz_block", new BlockData());
		registryMap.emplace("minecraft:quartz_pillar", new BlockData());
		registryMap.emplace("minecraft:quartz_slab", slab);
		registryMap.emplace("minecraft:quartz_stairs", new BlockData());
		registryMap.emplace("minecraft:rail", rail);
		registryMap.emplace("minecraft:red_banner", banner);
		registryMap.emplace("minecraft:red_bed", bed);
		registryMap.emplace("minecraft:red_carpet", carpet);
		registryMap.emplace("minecraft:red_concrete", concrete);
		registryMap.emplace("minecraft:red_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:red_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:red_mushroom", plant);
		registryMap.emplace("minecraft:red_mushroom_block", new BlockData());
		registryMap.emplace("minecraft:red_nether_bricks", bricks);
		registryMap.emplace("minecraft:red_sand", new BlockData());
		registryMap.emplace("minecraft:red_sandstone", sandstone);
		registryMap.emplace("minecraft:red_sandstone_slab", slab);
		registryMap.emplace("minecraft:red_sandstone_stairs", new BlockData());
		registryMap.emplace("minecraft:red_shulker_box", shulker);
		registryMap.emplace("minecraft:red_stained_glass", glass);
		registryMap.emplace("minecraft:red_stained_glass_pane", glass);
		registryMap.emplace("minecraft:red_terracotta", terracotta);
		registryMap.emplace("minecraft:red_tulip", plant);
		registryMap.emplace("minecraft:red_wall_banner", banner);
		registryMap.emplace("minecraft:red_wool", wool);
		registryMap.emplace("minecraft:redstone_block", new BlockData());
		registryMap.emplace("minecraft:redstone_lamp", new BlockData());
		registryMap.emplace("minecraft:redstone_ore", ore);
		registryMap.emplace("minecraft:redstone_torch", new BlockData());
		registryMap.emplace("minecraft:redstone_wall_torch", new BlockData());
		registryMap.emplace("minecraft:redstone_wire", new BlockData());
		registryMap.emplace("minecraft:repeater", new BlockData());
		registryMap.emplace("minecraft:repeating_command_block", new BlockData());
		registryMap.emplace("minecraft:rose_bush", plant);
		registryMap.emplace("minecraft:sand", new BlockData());
		registryMap.emplace("minecraft:sandstone", sandstone);
		registryMap.emplace("minecraft:sandstone_slab", slab);
		registryMap.emplace("minecraft:sandstone_stairs", new BlockData());
		registryMap.emplace("minecraft:sea_lantern", new BlockData());
		registryMap.emplace("minecraft:sea_pickle", plant);
		registryMap.emplace("minecraft:seagrass", plant);
		registryMap.emplace("minecraft:shulker_box", shulker);
		registryMap.emplace("minecraft:sign", new BlockData());
		registryMap.emplace("minecraft:skeleton_skull", head);
		registryMap.emplace("minecraft:skeleton_wall_skull", head);
		registryMap.emplace("minecraft:slime_block", new BlockData());
		registryMap.emplace("minecraft:smooth_quartz", new BlockData());
		registryMap.emplace("minecraft:smooth_red_sandstone", sandstone);
		registryMap.emplace("minecraft:smooth_sandstone", sandstone);
		registryMap.emplace("minecraft:smooth_stone", new BlockData());
		registryMap.emplace("minecraft:snow", new BlockData());
		registryMap.emplace("minecraft:snow_block", new BlockData());
		registryMap.emplace("minecraft:soul_sand", new BlockData());
		registryMap.emplace("minecraft:spawner", new BlockData());
		registryMap.emplace("minecraft:sponge", new BlockData());
		registryMap.emplace("minecraft:spruce_button", button);
		registryMap.emplace("minecraft:spruce_door", door);
		registryMap.emplace("minecraft:spruce_fence", fence);
		registryMap.emplace("minecraft:spruce_fence_gate", fence);
		registryMap.emplace("minecraft:spruce_leaves", leaves);
		registryMap.emplace("minecraft:spruce_log", log);
		registryMap.emplace("minecraft:spruce_planks", planks);
		registryMap.emplace("minecraft:spruce_pressure_plate", pressure_plate);
		registryMap.emplace("minecraft:spruce_sapling", sapling);
		registryMap.emplace("minecraft:spruce_slab", slab);
		registryMap.emplace("minecraft:spruce_stairs", new BlockData());
		registryMap.emplace("minecraft:spruce_trapdoor", trapdoor);
		registryMap.emplace("minecraft:spruce_wood", log);
		registryMap.emplace("minecraft:sticky_piston", new BlockData());
		registryMap.emplace("minecraft:stone", new BlockData());
		registryMap.emplace("minecraft:stone_brick_slab", slab);
		registryMap.emplace("minecraft:stone_brick_stairs", new BlockData());
		registryMap.emplace("minecraft:stone_bricks", bricks);
		registryMap.emplace("minecraft:stone_button", button);
		registryMap.emplace("minecraft:stone_pressure_plate", pressure_plate);
		registryMap.emplace("minecraft:stone_slab", slab);
		registryMap.emplace("minecraft:stripped_acacia_log", log);
		registryMap.emplace("minecraft:stripped_acacia_wood", log);
		registryMap.emplace("minecraft:stripped_birch_log", log);
		registryMap.emplace("minecraft:stripped_birch_wood", log);
		registryMap.emplace("minecraft:stripped_dark_oak_log", log);
		registryMap.emplace("minecraft:stripped_dark_oak_wood", log);
		registryMap.emplace("minecraft:stripped_jungle_log", log);
		registryMap.emplace("minecraft:stripped_jungle_wood", log);
		registryMap.emplace("minecraft:stripped_oak_log", log);
		registryMap.emplace("minecraft:stripped_oak_wood", log);
		registryMap.emplace("minecraft:stripped_spruce_log", log);
		registryMap.emplace("minecraft:stripped_spruce_wood", log);
		registryMap.emplace("minecraft:structure_block", new BlockData());
		registryMap.emplace("minecraft:structure_void", new BlockData());
		registryMap.emplace("minecraft:sugar_cane", plant);
		registryMap.emplace("minecraft:sunflower", plant);
		registryMap.emplace("minecraft:tall_grass", plant);
		registryMap.emplace("minecraft:tall_seagrass", plant);
		registryMap.emplace("minecraft:terracotta", terracotta);
		registryMap.emplace("minecraft:tnt", new BlockData());
		registryMap.emplace("minecraft:torch", new BlockData());
		registryMap.emplace("minecraft:trapped_chest", new BlockData());
		registryMap.emplace("minecraft:tripwire", new BlockData());
		registryMap.emplace("minecraft:tripwire_hook", new BlockData());
		registryMap.emplace("minecraft:tube_coral", plant);
		registryMap.emplace("minecraft:tube_coral_block", coral_block);
		registryMap.emplace("minecraft:tube_coral_fan", plant);
		registryMap.emplace("minecraft:tube_coral_wall_fan", plant);
		registryMap.emplace("minecraft:turtle_egg", new BlockData());
		registryMap.emplace("minecraft:vine", new BlockData());
		registryMap.emplace("minecraft:void_air", new BlockData());
		registryMap.emplace("minecraft:wall_sign", new BlockData());
		registryMap.emplace("minecraft:wall_torch", new BlockData());
		registryMap.emplace("minecraft:water", new BlockData());
		registryMap.emplace("minecraft:wet_sponge", new BlockData());
		registryMap.emplace("minecraft:wheat", plant);
		registryMap.emplace("minecraft:white_banner", banner);
		registryMap.emplace("minecraft:white_bed", bed);
		registryMap.emplace("minecraft:white_carpet", carpet);
		registryMap.emplace("minecraft:white_concrete", concrete);
		registryMap.emplace("minecraft:white_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:white_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:white_shulker_box", shulker);
		registryMap.emplace("minecraft:white_stained_glass", glass);
		registryMap.emplace("minecraft:white_stained_glass_pane", glass);
		registryMap.emplace("minecraft:white_terracotta", terracotta);
		registryMap.emplace("minecraft:white_tulip", plant);
		registryMap.emplace("minecraft:white_wall_banner", banner);
		registryMap.emplace("minecraft:white_wool", wool);
		registryMap.emplace("minecraft:wither_skeleton_skull", head);
		registryMap.emplace("minecraft:wither_skeleton_wall_skull", head);
		registryMap.emplace("minecraft:yellow_banner", banner);
		registryMap.emplace("minecraft:yellow_bed", bed);
		registryMap.emplace("minecraft:yellow_carpet", carpet);
		registryMap.emplace("minecraft:yellow_concrete", concrete);
		registryMap.emplace("minecraft:yellow_concrete_powder", concrete_powder);
		registryMap.emplace("minecraft:yellow_glazed_terracotta", terracotta);
		registryMap.emplace("minecraft:yellow_shulker_box", shulker);
		registryMap.emplace("minecraft:yellow_stained_glass", glass);
		registryMap.emplace("minecraft:yellow_stained_glass_pane", glass);
		registryMap.emplace("minecraft:yellow_terracotta", terracotta);
		registryMap.emplace("minecraft:yellow_wall_banner", banner);
		registryMap.emplace("minecraft:yellow_wool", wool);
		registryMap.emplace("minecraft:zombie_head", head);
		registryMap.emplace("minecraft:zombie_wall_head", head);


	}


    BlockData* BlockDataRegistry::getDataByName(std::string namespaceid)
    {
        return registryMap[namespaceid];
    }

    BlockDataRegistry* g_BlockDataRegistry;
}