#include "ItemRegistry.h"
#include "InverseMap.h"

namespace Minecraft::Server::Internal::Registry {
	ItemRegistry::ItemRegistry()
	{
	}

	ItemRegistry::~ItemRegistry()
	{
	}

	/*IMPORTED DIRECTLY FROM ITEMS.JSON & REFORMATTED - CAN BE DONE FOR ALL VERSIONS!*/
	void ItemRegistry::registerVanillaItems() {
        registryMap.emplace("minecraft:air",
            0
        );
        registryMap.emplace("minecraft:stone",
            1
        );
        registryMap.emplace("minecraft:granite",
            2
        );
        registryMap.emplace("minecraft:polished_granite",
            3
        );
        registryMap.emplace("minecraft:diorite",
            4
        );
        registryMap.emplace("minecraft:polished_diorite",
            5
        );
        registryMap.emplace("minecraft:andesite",
            6
        );
        registryMap.emplace("minecraft:polished_andesite",
            7
        );
        registryMap.emplace("minecraft:grass_block",
            8
        );
        registryMap.emplace("minecraft:dirt",
            9
        );
        registryMap.emplace("minecraft:coarse_dirt",
            10
        );
        registryMap.emplace("minecraft:podzol",
            11
        );
        registryMap.emplace("minecraft:cobblestone",
            12
        );
        registryMap.emplace("minecraft:oak_planks",
            13
        );
        registryMap.emplace("minecraft:spruce_planks",
            14
        );
        registryMap.emplace("minecraft:birch_planks",
            15
        );
        registryMap.emplace("minecraft:jungle_planks",
            16
        );
        registryMap.emplace("minecraft:acacia_planks",
            17
        );
        registryMap.emplace("minecraft:dark_oak_planks",
            18
        );
        registryMap.emplace("minecraft:oak_sapling",
            19
        );
        registryMap.emplace("minecraft:spruce_sapling",
            20
        );
        registryMap.emplace("minecraft:birch_sapling",
            21
        );
        registryMap.emplace("minecraft:jungle_sapling",
            22
        );
        registryMap.emplace("minecraft:acacia_sapling",
            23
        );
        registryMap.emplace("minecraft:dark_oak_sapling",
            24
        );
        registryMap.emplace("minecraft:bedrock",
            25
        );
        registryMap.emplace("minecraft:sand",
            26
        );
        registryMap.emplace("minecraft:red_sand",
            27
        );
        registryMap.emplace("minecraft:gravel",
            28
        );
        registryMap.emplace("minecraft:gold_ore",
            29
        );
        registryMap.emplace("minecraft:iron_ore",
            30
        );
        registryMap.emplace("minecraft:coal_ore",
            31
        );
        registryMap.emplace("minecraft:oak_log",
            32
        );
        registryMap.emplace("minecraft:spruce_log",
            33
        );
        registryMap.emplace("minecraft:birch_log",
            34
        );
        registryMap.emplace("minecraft:jungle_log",
            35
        );
        registryMap.emplace("minecraft:acacia_log",
            36
        );
        registryMap.emplace("minecraft:dark_oak_log",
            37
        );
        registryMap.emplace("minecraft:stripped_oak_log",
            38
        );
        registryMap.emplace("minecraft:stripped_spruce_log",
            39
        );
        registryMap.emplace("minecraft:stripped_birch_log",
            40
        );
        registryMap.emplace("minecraft:stripped_jungle_log",
            41
        );
        registryMap.emplace("minecraft:stripped_acacia_log",
            42
        );
        registryMap.emplace("minecraft:stripped_dark_oak_log",
            43
        );
        registryMap.emplace("minecraft:stripped_oak_wood",
            44
        );
        registryMap.emplace("minecraft:stripped_spruce_wood",
            45
        );
        registryMap.emplace("minecraft:stripped_birch_wood",
            46
        );
        registryMap.emplace("minecraft:stripped_jungle_wood",
            47
        );
        registryMap.emplace("minecraft:stripped_acacia_wood",
            48
        );
        registryMap.emplace("minecraft:stripped_dark_oak_wood",
            49
        );
        registryMap.emplace("minecraft:oak_wood",
            50
        );
        registryMap.emplace("minecraft:spruce_wood",
            51
        );
        registryMap.emplace("minecraft:birch_wood",
            52
        );
        registryMap.emplace("minecraft:jungle_wood",
            53
        );
        registryMap.emplace("minecraft:acacia_wood",
            54
        );
        registryMap.emplace("minecraft:dark_oak_wood",
            55
        );
        registryMap.emplace("minecraft:oak_leaves",
            56
        );
        registryMap.emplace("minecraft:spruce_leaves",
            57
        );
        registryMap.emplace("minecraft:birch_leaves",
            58
        );
        registryMap.emplace("minecraft:jungle_leaves",
            59
        );
        registryMap.emplace("minecraft:acacia_leaves",
            60
        );
        registryMap.emplace("minecraft:dark_oak_leaves",
            61
        );
        registryMap.emplace("minecraft:sponge",
            62
        );
        registryMap.emplace("minecraft:wet_sponge",
            63
        );
        registryMap.emplace("minecraft:glass",
            64
        );
        registryMap.emplace("minecraft:lapis_ore",
            65
        );
        registryMap.emplace("minecraft:lapis_block",
            66
        );
        registryMap.emplace("minecraft:dispenser",
            67
        );
        registryMap.emplace("minecraft:sandstone",
            68
        );
        registryMap.emplace("minecraft:chiseled_sandstone",
            69
        );
        registryMap.emplace("minecraft:cut_sandstone",
            70
        );
        registryMap.emplace("minecraft:note_block",
            71
        );
        registryMap.emplace("minecraft:powered_rail",
            72
        );
        registryMap.emplace("minecraft:detector_rail",
            73
        );
        registryMap.emplace("minecraft:sticky_piston",
            74
        );
        registryMap.emplace("minecraft:cobweb",
            75
        );
        registryMap.emplace("minecraft:grass",
            76
        );
        registryMap.emplace("minecraft:fern",
            77
        );
        registryMap.emplace("minecraft:dead_bush",
            78
        );
        registryMap.emplace("minecraft:seagrass",
            79
        );
        registryMap.emplace("minecraft:sea_pickle",
            80
        );
        registryMap.emplace("minecraft:piston",
            81
        );
        registryMap.emplace("minecraft:white_wool",
            82
        );
        registryMap.emplace("minecraft:orange_wool",
            83
        );
        registryMap.emplace("minecraft:magenta_wool",
            84
        );
        registryMap.emplace("minecraft:light_blue_wool",
            85
        );
        registryMap.emplace("minecraft:yellow_wool",
            86
        );
        registryMap.emplace("minecraft:lime_wool",
            87
        );
        registryMap.emplace("minecraft:pink_wool",
            88
        );
        registryMap.emplace("minecraft:gray_wool",
            89
        );
        registryMap.emplace("minecraft:light_gray_wool",
            90
        );
        registryMap.emplace("minecraft:cyan_wool",
            91
        );
        registryMap.emplace("minecraft:purple_wool",
            92
        );
        registryMap.emplace("minecraft:blue_wool",
            93
        );
        registryMap.emplace("minecraft:brown_wool",
            94
        );
        registryMap.emplace("minecraft:green_wool",
            95
        );
        registryMap.emplace("minecraft:red_wool",
            96
        );
        registryMap.emplace("minecraft:black_wool",
            97
        );
        registryMap.emplace("minecraft:dandelion",
            98
        );
        registryMap.emplace("minecraft:poppy",
            99
        );
        registryMap.emplace("minecraft:blue_orchid",
            100
        );
        registryMap.emplace("minecraft:allium",
            101
        );
        registryMap.emplace("minecraft:azure_bluet",
            102
        );
        registryMap.emplace("minecraft:red_tulip",
            103
        );
        registryMap.emplace("minecraft:orange_tulip",
            104
        );
        registryMap.emplace("minecraft:white_tulip",
            105
        );
        registryMap.emplace("minecraft:pink_tulip",
            106
        );
        registryMap.emplace("minecraft:oxeye_daisy",
            107
        );
        registryMap.emplace("minecraft:brown_mushroom",
            108
        );
        registryMap.emplace("minecraft:red_mushroom",
            109
        );
        registryMap.emplace("minecraft:gold_block",
            110
        );
        registryMap.emplace("minecraft:iron_block",
            111
        );
        registryMap.emplace("minecraft:oak_slab",
            112
        );
        registryMap.emplace("minecraft:spruce_slab",
            113
        );
        registryMap.emplace("minecraft:birch_slab",
            114
        );
        registryMap.emplace("minecraft:jungle_slab",
            115
        );
        registryMap.emplace("minecraft:acacia_slab",
            116
        );
        registryMap.emplace("minecraft:dark_oak_slab",
            117
        );
        registryMap.emplace("minecraft:stone_slab",
            118
        );
        registryMap.emplace("minecraft:sandstone_slab",
            119
        );
        registryMap.emplace("minecraft:petrified_oak_slab",
            120
        );
        registryMap.emplace("minecraft:cobblestone_slab",
            121
        );
        registryMap.emplace("minecraft:brick_slab",
            122
        );
        registryMap.emplace("minecraft:stone_brick_slab",
            123
        );
        registryMap.emplace("minecraft:nether_brick_slab",
            124
        );
        registryMap.emplace("minecraft:quartz_slab",
            125
        );
        registryMap.emplace("minecraft:red_sandstone_slab",
            126
        );
        registryMap.emplace("minecraft:purpur_slab",
            127
        );
        registryMap.emplace("minecraft:prismarine_slab",
            128
        );
        registryMap.emplace("minecraft:prismarine_brick_slab",
            129
        );
        registryMap.emplace("minecraft:dark_prismarine_slab",
            130
        );
        registryMap.emplace("minecraft:smooth_quartz",
            131
        );
        registryMap.emplace("minecraft:smooth_red_sandstone",
            132
        );
        registryMap.emplace("minecraft:smooth_sandstone",
            133
        );
        registryMap.emplace("minecraft:smooth_stone",
            134
        );
        registryMap.emplace("minecraft:bricks",
            135
        );
        registryMap.emplace("minecraft:tnt",
            136
        );
        registryMap.emplace("minecraft:bookshelf",
            137
        );
        registryMap.emplace("minecraft:mossy_cobblestone",
            138
        );
        registryMap.emplace("minecraft:obsidian",
            139
        );
        registryMap.emplace("minecraft:torch",
            140
        );
        registryMap.emplace("minecraft:end_rod",
            141
        );
        registryMap.emplace("minecraft:chorus_plant",
            142
        );
        registryMap.emplace("minecraft:chorus_flower",
            143
        );
        registryMap.emplace("minecraft:purpur_block",
            144
        );
        registryMap.emplace("minecraft:purpur_pillar",
            145
        );
        registryMap.emplace("minecraft:purpur_stairs",
            146
        );
        registryMap.emplace("minecraft:spawner",
            147
        );
        registryMap.emplace("minecraft:oak_stairs",
            148
        );
        registryMap.emplace("minecraft:chest",
            149
        );
        registryMap.emplace("minecraft:diamond_ore",
            150
        );
        registryMap.emplace("minecraft:diamond_block",
            151
        );
        registryMap.emplace("minecraft:crafting_table",
            152
        );
        registryMap.emplace("minecraft:farmland",
            153
        );
        registryMap.emplace("minecraft:furnace",
            154
        );
        registryMap.emplace("minecraft:ladder",
            155
        );
        registryMap.emplace("minecraft:rail",
            156
        );
        registryMap.emplace("minecraft:cobblestone_stairs",
            157
        );
        registryMap.emplace("minecraft:lever",
            158
        );
        registryMap.emplace("minecraft:stone_pressure_plate",
            159
        );
        registryMap.emplace("minecraft:oak_pressure_plate",
            160
        );
        registryMap.emplace("minecraft:spruce_pressure_plate",
            161
        );
        registryMap.emplace("minecraft:birch_pressure_plate",
            162
        );
        registryMap.emplace("minecraft:jungle_pressure_plate",
            163
        );
        registryMap.emplace("minecraft:acacia_pressure_plate",
            164
        );
        registryMap.emplace("minecraft:dark_oak_pressure_plate",
            165
        );
        registryMap.emplace("minecraft:redstone_ore",
            166
        );
        registryMap.emplace("minecraft:redstone_torch",
            167
        );
        registryMap.emplace("minecraft:stone_button",
            168
        );
        registryMap.emplace("minecraft:snow",
            169
        );
        registryMap.emplace("minecraft:ice",
            170
        );
        registryMap.emplace("minecraft:snow_block",
            171
        );
        registryMap.emplace("minecraft:cactus",
            172
        );
        registryMap.emplace("minecraft:clay",
            173
        );
        registryMap.emplace("minecraft:jukebox",
            174
        );
        registryMap.emplace("minecraft:oak_fence",
            175
        );
        registryMap.emplace("minecraft:spruce_fence",
            176
        );
        registryMap.emplace("minecraft:birch_fence",
            177
        );
        registryMap.emplace("minecraft:jungle_fence",
            178
        );
        registryMap.emplace("minecraft:acacia_fence",
            179
        );
        registryMap.emplace("minecraft:dark_oak_fence",
            180
        );
        registryMap.emplace("minecraft:pumpkin",
            181
        );
        registryMap.emplace("minecraft:carved_pumpkin",
            182
        );
        registryMap.emplace("minecraft:netherrack",
            183
        );
        registryMap.emplace("minecraft:soul_sand",
            184
        );
        registryMap.emplace("minecraft:glowstone",
            185
        );
        registryMap.emplace("minecraft:jack_o_lantern",
            186
        );
        registryMap.emplace("minecraft:oak_trapdoor",
            187
        );
        registryMap.emplace("minecraft:spruce_trapdoor",
            188
        );
        registryMap.emplace("minecraft:birch_trapdoor",
            189
        );
        registryMap.emplace("minecraft:jungle_trapdoor",
            190
        );
        registryMap.emplace("minecraft:acacia_trapdoor",
            191
        );
        registryMap.emplace("minecraft:dark_oak_trapdoor",
            192
        );
        registryMap.emplace("minecraft:infested_stone",
            193
        );
        registryMap.emplace("minecraft:infested_cobblestone",
            194
        );
        registryMap.emplace("minecraft:infested_stone_bricks",
            195
        );
        registryMap.emplace("minecraft:infested_mossy_stone_bricks",
            196
        );
        registryMap.emplace("minecraft:infested_cracked_stone_bricks",
            197
        );
        registryMap.emplace("minecraft:infested_chiseled_stone_bricks",
            198
        );
        registryMap.emplace("minecraft:stone_bricks",
            199
        );
        registryMap.emplace("minecraft:mossy_stone_bricks",
            200
        );
        registryMap.emplace("minecraft:cracked_stone_bricks",
            201
        );
        registryMap.emplace("minecraft:chiseled_stone_bricks",
            202
        );
        registryMap.emplace("minecraft:brown_mushroom_block",
            203
        );
        registryMap.emplace("minecraft:red_mushroom_block",
            204
        );
        registryMap.emplace("minecraft:mushroom_stem",
            205
        );
        registryMap.emplace("minecraft:iron_bars",
            206
        );
        registryMap.emplace("minecraft:glass_pane",
            207
        );
        registryMap.emplace("minecraft:melon",
            208
        );
        registryMap.emplace("minecraft:vine",
            209
        );
        registryMap.emplace("minecraft:oak_fence_gate",
            210
        );
        registryMap.emplace("minecraft:spruce_fence_gate",
            211
        );
        registryMap.emplace("minecraft:birch_fence_gate",
            212
        );
        registryMap.emplace("minecraft:jungle_fence_gate",
            213
        );
        registryMap.emplace("minecraft:acacia_fence_gate",
            214
        );
        registryMap.emplace("minecraft:dark_oak_fence_gate",
            215
        );
        registryMap.emplace("minecraft:brick_stairs",
            216
        );
        registryMap.emplace("minecraft:stone_brick_stairs",
            217
        );
        registryMap.emplace("minecraft:mycelium",
            218
        );
        registryMap.emplace("minecraft:lily_pad",
            219
        );
        registryMap.emplace("minecraft:nether_bricks",
            220
        );
        registryMap.emplace("minecraft:nether_brick_fence",
            221
        );
        registryMap.emplace("minecraft:nether_brick_stairs",
            222
        );
        registryMap.emplace("minecraft:enchanting_table",
            223
        );
        registryMap.emplace("minecraft:end_portal_frame",
            224
        );
        registryMap.emplace("minecraft:end_stone",
            225
        );
        registryMap.emplace("minecraft:end_stone_bricks",
            226
        );
        registryMap.emplace("minecraft:dragon_egg",
            227
        );
        registryMap.emplace("minecraft:redstone_lamp",
            228
        );
        registryMap.emplace("minecraft:sandstone_stairs",
            229
        );
        registryMap.emplace("minecraft:emerald_ore",
            230
        );
        registryMap.emplace("minecraft:ender_chest",
            231
        );
        registryMap.emplace("minecraft:tripwire_hook",
            232
        );
        registryMap.emplace("minecraft:emerald_block",
            233
        );
        registryMap.emplace("minecraft:spruce_stairs",
            234
        );
        registryMap.emplace("minecraft:birch_stairs",
            235
        );
        registryMap.emplace("minecraft:jungle_stairs",
            236
        );
        registryMap.emplace("minecraft:command_block",
            237
        );
        registryMap.emplace("minecraft:beacon",
            238
        );
        registryMap.emplace("minecraft:cobblestone_wall",
            239
        );
        registryMap.emplace("minecraft:mossy_cobblestone_wall",
            240
        );
        registryMap.emplace("minecraft:oak_button",
            241
        );
        registryMap.emplace("minecraft:spruce_button",
            242
        );
        registryMap.emplace("minecraft:birch_button",
            243
        );
        registryMap.emplace("minecraft:jungle_button",
            244
        );
        registryMap.emplace("minecraft:acacia_button",
            245
        );
        registryMap.emplace("minecraft:dark_oak_button",
            246
        );
        registryMap.emplace("minecraft:anvil",
            247
        );
        registryMap.emplace("minecraft:chipped_anvil",
            248
        );
        registryMap.emplace("minecraft:damaged_anvil",
            249
        );
        registryMap.emplace("minecraft:trapped_chest",
            250
        );
        registryMap.emplace("minecraft:light_weighted_pressure_plate",
            251
        );
        registryMap.emplace("minecraft:heavy_weighted_pressure_plate",
            252
        );
        registryMap.emplace("minecraft:daylight_detector",
            253
        );
        registryMap.emplace("minecraft:redstone_block",
            254
        );
        registryMap.emplace("minecraft:nether_quartz_ore",
            255
        );
        registryMap.emplace("minecraft:hopper",
            256
        );
        registryMap.emplace("minecraft:chiseled_quartz_block",
            257
        );
        registryMap.emplace("minecraft:quartz_block",
            258
        );
        registryMap.emplace("minecraft:quartz_pillar",
            259
        );
        registryMap.emplace("minecraft:quartz_stairs",
            260
        );
        registryMap.emplace("minecraft:activator_rail",
            261
        );
        registryMap.emplace("minecraft:dropper",
            262
        );
        registryMap.emplace("minecraft:white_terracotta",
            263
        );
        registryMap.emplace("minecraft:orange_terracotta",
            264
        );
        registryMap.emplace("minecraft:magenta_terracotta",
            265
        );
        registryMap.emplace("minecraft:light_blue_terracotta",
            266
        );
        registryMap.emplace("minecraft:yellow_terracotta",
            267
        );
        registryMap.emplace("minecraft:lime_terracotta",
            268
        );
        registryMap.emplace("minecraft:pink_terracotta",
            269
        );
        registryMap.emplace("minecraft:gray_terracotta",
            270
        );
        registryMap.emplace("minecraft:light_gray_terracotta",
            271
        );
        registryMap.emplace("minecraft:cyan_terracotta",
            272
        );
        registryMap.emplace("minecraft:purple_terracotta",
            273
        );
        registryMap.emplace("minecraft:blue_terracotta",
            274
        );
        registryMap.emplace("minecraft:brown_terracotta",
            275
        );
        registryMap.emplace("minecraft:green_terracotta",
            276
        );
        registryMap.emplace("minecraft:red_terracotta",
            277
        );
        registryMap.emplace("minecraft:black_terracotta",
            278
        );
        registryMap.emplace("minecraft:barrier",
            279
        );
        registryMap.emplace("minecraft:iron_trapdoor",
            280
        );
        registryMap.emplace("minecraft:hay_block",
            281
        );
        registryMap.emplace("minecraft:white_carpet",
            282
        );
        registryMap.emplace("minecraft:orange_carpet",
            283
        );
        registryMap.emplace("minecraft:magenta_carpet",
            284
        );
        registryMap.emplace("minecraft:light_blue_carpet",
            285
        );
        registryMap.emplace("minecraft:yellow_carpet",
            286
        );
        registryMap.emplace("minecraft:lime_carpet",
            287
        );
        registryMap.emplace("minecraft:pink_carpet",
            288
        );
        registryMap.emplace("minecraft:gray_carpet",
            289
        );
        registryMap.emplace("minecraft:light_gray_carpet",
            290
        );
        registryMap.emplace("minecraft:cyan_carpet",
            291
        );
        registryMap.emplace("minecraft:purple_carpet",
            292
        );
        registryMap.emplace("minecraft:blue_carpet",
            293
        );
        registryMap.emplace("minecraft:brown_carpet",
            294
        );
        registryMap.emplace("minecraft:green_carpet",
            295
        );
        registryMap.emplace("minecraft:red_carpet",
            296
        );
        registryMap.emplace("minecraft:black_carpet",
            297
        );
        registryMap.emplace("minecraft:terracotta",
            298
        );
        registryMap.emplace("minecraft:coal_block",
            299
        );
        registryMap.emplace("minecraft:packed_ice",
            300
        );
        registryMap.emplace("minecraft:acacia_stairs",
            301
        );
        registryMap.emplace("minecraft:dark_oak_stairs",
            302
        );
        registryMap.emplace("minecraft:slime_block",
            303
        );
        registryMap.emplace("minecraft:grass_path",
            304
        );
        registryMap.emplace("minecraft:sunflower",
            305
        );
        registryMap.emplace("minecraft:lilac",
            306
        );
        registryMap.emplace("minecraft:rose_bush",
            307
        );
        registryMap.emplace("minecraft:peony",
            308
        );
        registryMap.emplace("minecraft:tall_grass",
            309
        );
        registryMap.emplace("minecraft:large_fern",
            310
        );
        registryMap.emplace("minecraft:white_stained_glass",
            311
        );
        registryMap.emplace("minecraft:orange_stained_glass",
            312
        );
        registryMap.emplace("minecraft:magenta_stained_glass",
            313
        );
        registryMap.emplace("minecraft:light_blue_stained_glass",
            314
        );
        registryMap.emplace("minecraft:yellow_stained_glass",
            315
        );
        registryMap.emplace("minecraft:lime_stained_glass",
            316
        );
        registryMap.emplace("minecraft:pink_stained_glass",
            317
        );
        registryMap.emplace("minecraft:gray_stained_glass",
            318
        );
        registryMap.emplace("minecraft:light_gray_stained_glass",
            319
        );
        registryMap.emplace("minecraft:cyan_stained_glass",
            320
        );
        registryMap.emplace("minecraft:purple_stained_glass",
            321
        );
        registryMap.emplace("minecraft:blue_stained_glass",
            322
        );
        registryMap.emplace("minecraft:brown_stained_glass",
            323
        );
        registryMap.emplace("minecraft:green_stained_glass",
            324
        );
        registryMap.emplace("minecraft:red_stained_glass",
            325
        );
        registryMap.emplace("minecraft:black_stained_glass",
            326
        );
        registryMap.emplace("minecraft:white_stained_glass_pane",
            327
        );
        registryMap.emplace("minecraft:orange_stained_glass_pane",
            328
        );
        registryMap.emplace("minecraft:magenta_stained_glass_pane",
            329
        );
        registryMap.emplace("minecraft:light_blue_stained_glass_pane",
            330
        );
        registryMap.emplace("minecraft:yellow_stained_glass_pane",
            331
        );
        registryMap.emplace("minecraft:lime_stained_glass_pane",
            332
        );
        registryMap.emplace("minecraft:pink_stained_glass_pane",
            333
        );
        registryMap.emplace("minecraft:gray_stained_glass_pane",
            334
        );
        registryMap.emplace("minecraft:light_gray_stained_glass_pane",
            335
        );
        registryMap.emplace("minecraft:cyan_stained_glass_pane",
            336
        );
        registryMap.emplace("minecraft:purple_stained_glass_pane",
            337
        );
        registryMap.emplace("minecraft:blue_stained_glass_pane",
            338
        );
        registryMap.emplace("minecraft:brown_stained_glass_pane",
            339
        );
        registryMap.emplace("minecraft:green_stained_glass_pane",
            340
        );
        registryMap.emplace("minecraft:red_stained_glass_pane",
            341
        );
        registryMap.emplace("minecraft:black_stained_glass_pane",
            342
        );
        registryMap.emplace("minecraft:prismarine",
            343
        );
        registryMap.emplace("minecraft:prismarine_bricks",
            344
        );
        registryMap.emplace("minecraft:dark_prismarine",
            345
        );
        registryMap.emplace("minecraft:prismarine_stairs",
            346
        );
        registryMap.emplace("minecraft:prismarine_brick_stairs",
            347
        );
        registryMap.emplace("minecraft:dark_prismarine_stairs",
            348
        );
        registryMap.emplace("minecraft:sea_lantern",
            349
        );
        registryMap.emplace("minecraft:red_sandstone",
            350
        );
        registryMap.emplace("minecraft:chiseled_red_sandstone",
            351
        );
        registryMap.emplace("minecraft:cut_red_sandstone",
            352
        );
        registryMap.emplace("minecraft:red_sandstone_stairs",
            353
        );
        registryMap.emplace("minecraft:repeating_command_block",
            354
        );
        registryMap.emplace("minecraft:chain_command_block",
            355
        );
        registryMap.emplace("minecraft:magma_block",
            356
        );
        registryMap.emplace("minecraft:nether_wart_block",
            357
        );
        registryMap.emplace("minecraft:red_nether_bricks",
            358
        );
        registryMap.emplace("minecraft:bone_block",
            359
        );
        registryMap.emplace("minecraft:structure_void",
            360
        );
        registryMap.emplace("minecraft:observer",
            361
        );
        registryMap.emplace("minecraft:shulker_box",
            362
        );
        registryMap.emplace("minecraft:white_shulker_box",
            363
        );
        registryMap.emplace("minecraft:orange_shulker_box",
            364
        );
        registryMap.emplace("minecraft:magenta_shulker_box",
            365
        );
        registryMap.emplace("minecraft:light_blue_shulker_box",
            366
        );
        registryMap.emplace("minecraft:yellow_shulker_box",
            367
        );
        registryMap.emplace("minecraft:lime_shulker_box",
            368
        );
        registryMap.emplace("minecraft:pink_shulker_box",
            369
        );
        registryMap.emplace("minecraft:gray_shulker_box",
            370
        );
        registryMap.emplace("minecraft:light_gray_shulker_box",
            371
        );
        registryMap.emplace("minecraft:cyan_shulker_box",
            372
        );
        registryMap.emplace("minecraft:purple_shulker_box",
            373
        );
        registryMap.emplace("minecraft:blue_shulker_box",
            374
        );
        registryMap.emplace("minecraft:brown_shulker_box",
            375
        );
        registryMap.emplace("minecraft:green_shulker_box",
            376
        );
        registryMap.emplace("minecraft:red_shulker_box",
            377
        );
        registryMap.emplace("minecraft:black_shulker_box",
            378
        );
        registryMap.emplace("minecraft:white_glazed_terracotta",
            379
        );
        registryMap.emplace("minecraft:orange_glazed_terracotta",
            380
        );
        registryMap.emplace("minecraft:magenta_glazed_terracotta",
            381
        );
        registryMap.emplace("minecraft:light_blue_glazed_terracotta",
            382
        );
        registryMap.emplace("minecraft:yellow_glazed_terracotta",
            383
        );
        registryMap.emplace("minecraft:lime_glazed_terracotta",
            384
        );
        registryMap.emplace("minecraft:pink_glazed_terracotta",
            385
        );
        registryMap.emplace("minecraft:gray_glazed_terracotta",
            386
        );
        registryMap.emplace("minecraft:light_gray_glazed_terracotta",
            387
        );
        registryMap.emplace("minecraft:cyan_glazed_terracotta",
            388
        );
        registryMap.emplace("minecraft:purple_glazed_terracotta",
            389
        );
        registryMap.emplace("minecraft:blue_glazed_terracotta",
            390
        );
        registryMap.emplace("minecraft:brown_glazed_terracotta",
            391
        );
        registryMap.emplace("minecraft:green_glazed_terracotta",
            392
        );
        registryMap.emplace("minecraft:red_glazed_terracotta",
            393
        );
        registryMap.emplace("minecraft:black_glazed_terracotta",
            394
        );
        registryMap.emplace("minecraft:white_concrete",
            395
        );
        registryMap.emplace("minecraft:orange_concrete",
            396
        );
        registryMap.emplace("minecraft:magenta_concrete",
            397
        );
        registryMap.emplace("minecraft:light_blue_concrete",
            398
        );
        registryMap.emplace("minecraft:yellow_concrete",
            399
        );
        registryMap.emplace("minecraft:lime_concrete",
            400
        );
        registryMap.emplace("minecraft:pink_concrete",
            401
        );
        registryMap.emplace("minecraft:gray_concrete",
            402
        );
        registryMap.emplace("minecraft:light_gray_concrete",
            403
        );
        registryMap.emplace("minecraft:cyan_concrete",
            404
        );
        registryMap.emplace("minecraft:purple_concrete",
            405
        );
        registryMap.emplace("minecraft:blue_concrete",
            406
        );
        registryMap.emplace("minecraft:brown_concrete",
            407
        );
        registryMap.emplace("minecraft:green_concrete",
            408
        );
        registryMap.emplace("minecraft:red_concrete",
            409
        );
        registryMap.emplace("minecraft:black_concrete",
            410
        );
        registryMap.emplace("minecraft:white_concrete_powder",
            411
        );
        registryMap.emplace("minecraft:orange_concrete_powder",
            412
        );
        registryMap.emplace("minecraft:magenta_concrete_powder",
            413
        );
        registryMap.emplace("minecraft:light_blue_concrete_powder",
            414
        );
        registryMap.emplace("minecraft:yellow_concrete_powder",
            415
        );
        registryMap.emplace("minecraft:lime_concrete_powder",
            416
        );
        registryMap.emplace("minecraft:pink_concrete_powder",
            417
        );
        registryMap.emplace("minecraft:gray_concrete_powder",
            418
        );
        registryMap.emplace("minecraft:light_gray_concrete_powder",
            419
        );
        registryMap.emplace("minecraft:cyan_concrete_powder",
            420
        );
        registryMap.emplace("minecraft:purple_concrete_powder",
            421
        );
        registryMap.emplace("minecraft:blue_concrete_powder",
            422
        );
        registryMap.emplace("minecraft:brown_concrete_powder",
            423
        );
        registryMap.emplace("minecraft:green_concrete_powder",
            424
        );
        registryMap.emplace("minecraft:red_concrete_powder",
            425
        );
        registryMap.emplace("minecraft:black_concrete_powder",
            426
        );
        registryMap.emplace("minecraft:turtle_egg",
            427
        );
        registryMap.emplace("minecraft:dead_tube_coral_block",
            428
        );
        registryMap.emplace("minecraft:dead_brain_coral_block",
            429
        );
        registryMap.emplace("minecraft:dead_bubble_coral_block",
            430
        );
        registryMap.emplace("minecraft:dead_fire_coral_block",
            431
        );
        registryMap.emplace("minecraft:dead_horn_coral_block",
            432
        );
        registryMap.emplace("minecraft:tube_coral_block",
            433
        );
        registryMap.emplace("minecraft:brain_coral_block",
            434
        );
        registryMap.emplace("minecraft:bubble_coral_block",
            435
        );
        registryMap.emplace("minecraft:fire_coral_block",
            436
        );
        registryMap.emplace("minecraft:horn_coral_block",
            437
        );
        registryMap.emplace("minecraft:tube_coral",
            438
        );
        registryMap.emplace("minecraft:brain_coral",
            439
        );
        registryMap.emplace("minecraft:bubble_coral",
            440
        );
        registryMap.emplace("minecraft:fire_coral",
            441
        );
        registryMap.emplace("minecraft:horn_coral",
            442
        );
        registryMap.emplace("minecraft:dead_brain_coral",
            443
        );
        registryMap.emplace("minecraft:dead_bubble_coral",
            444
        );
        registryMap.emplace("minecraft:dead_fire_coral",
            445
        );
        registryMap.emplace("minecraft:dead_horn_coral",
            446
        );
        registryMap.emplace("minecraft:dead_tube_coral",
            447
        );
        registryMap.emplace("minecraft:tube_coral_fan",
            448
        );
        registryMap.emplace("minecraft:brain_coral_fan",
            449
        );
        registryMap.emplace("minecraft:bubble_coral_fan",
            450
        );
        registryMap.emplace("minecraft:fire_coral_fan",
            451
        );
        registryMap.emplace("minecraft:horn_coral_fan",
            452
        );
        registryMap.emplace("minecraft:dead_tube_coral_fan",
            453
        );
        registryMap.emplace("minecraft:dead_brain_coral_fan",
            454
        );
        registryMap.emplace("minecraft:dead_bubble_coral_fan",
            455
        );
        registryMap.emplace("minecraft:dead_fire_coral_fan",
            456
        );
        registryMap.emplace("minecraft:dead_horn_coral_fan",
            457
        );
        registryMap.emplace("minecraft:blue_ice",
            458
        );
        registryMap.emplace("minecraft:conduit",
            459
        );
        registryMap.emplace("minecraft:iron_door",
            460
        );
        registryMap.emplace("minecraft:oak_door",
            461
        );
        registryMap.emplace("minecraft:spruce_door",
            462
        );
        registryMap.emplace("minecraft:birch_door",
            463
        );
        registryMap.emplace("minecraft:jungle_door",
            464
        );
        registryMap.emplace("minecraft:acacia_door",
            465
        );
        registryMap.emplace("minecraft:dark_oak_door",
            466
        );
        registryMap.emplace("minecraft:repeater",
            467
        );
        registryMap.emplace("minecraft:comparator",
            468
        );
        registryMap.emplace("minecraft:structure_block",
            469
        );
        registryMap.emplace("minecraft:turtle_helmet",
            470
        );
        registryMap.emplace("minecraft:scute",
            471
        );
        registryMap.emplace("minecraft:iron_shovel",
            472
        );
        registryMap.emplace("minecraft:iron_pickaxe",
            473
        );
        registryMap.emplace("minecraft:iron_axe",
            474
        );
        registryMap.emplace("minecraft:flint_and_steel",
            475
        );
        registryMap.emplace("minecraft:apple",
            476
        );
        registryMap.emplace("minecraft:bow",
            477
        );
        registryMap.emplace("minecraft:arrow",
            478
        );
        registryMap.emplace("minecraft:coal",
            479
        );
        registryMap.emplace("minecraft:charcoal",
            480
        );
        registryMap.emplace("minecraft:diamond",
            481
        );
        registryMap.emplace("minecraft:iron_ingot",
            482
        );
        registryMap.emplace("minecraft:gold_ingot",
            483
        );
        registryMap.emplace("minecraft:iron_sword",
            484
        );
        registryMap.emplace("minecraft:wooden_sword",
            485
        );
        registryMap.emplace("minecraft:wooden_shovel",
            486
        );
        registryMap.emplace("minecraft:wooden_pickaxe",
            487
        );
        registryMap.emplace("minecraft:wooden_axe",
            488
        );
        registryMap.emplace("minecraft:stone_sword",
            489
        );
        registryMap.emplace("minecraft:stone_shovel",
            490
        );
        registryMap.emplace("minecraft:stone_pickaxe",
            491
        );
        registryMap.emplace("minecraft:stone_axe",
            492
        );
        registryMap.emplace("minecraft:diamond_sword",
            493
        );
        registryMap.emplace("minecraft:diamond_shovel",
            494
        );
        registryMap.emplace("minecraft:diamond_pickaxe",
            495
        );
        registryMap.emplace("minecraft:diamond_axe",
            496
        );
        registryMap.emplace("minecraft:stick",
            497
        );
        registryMap.emplace("minecraft:bowl",
            498
        );
        registryMap.emplace("minecraft:mushroom_stew",
            499
        );
        registryMap.emplace("minecraft:golden_sword",
            500
        );
        registryMap.emplace("minecraft:golden_shovel",
            501
        );
        registryMap.emplace("minecraft:golden_pickaxe",
            502
        );
        registryMap.emplace("minecraft:golden_axe",
            503
        );
        registryMap.emplace("minecraft:string",
            504
        );
        registryMap.emplace("minecraft:feather",
            505
        );
        registryMap.emplace("minecraft:gunpowder",
            506
        );
        registryMap.emplace("minecraft:wooden_hoe",
            507
        );
        registryMap.emplace("minecraft:stone_hoe",
            508
        );
        registryMap.emplace("minecraft:iron_hoe",
            509
        );
        registryMap.emplace("minecraft:diamond_hoe",
            510
        );
        registryMap.emplace("minecraft:golden_hoe",
            511
        );
        registryMap.emplace("minecraft:wheat_seeds",
            512
        );
        registryMap.emplace("minecraft:wheat",
            513
        );
        registryMap.emplace("minecraft:bread",
            514
        );
        registryMap.emplace("minecraft:leather_helmet",
            515
        );
        registryMap.emplace("minecraft:leather_chestplate",
            516
        );
        registryMap.emplace("minecraft:leather_leggings",
            517
        );
        registryMap.emplace("minecraft:leather_boots",
            518
        );
        registryMap.emplace("minecraft:chainmail_helmet",
            519
        );
        registryMap.emplace("minecraft:chainmail_chestplate",
            520
        );
        registryMap.emplace("minecraft:chainmail_leggings",
            521
        );
        registryMap.emplace("minecraft:chainmail_boots",
            522
        );
        registryMap.emplace("minecraft:iron_helmet",
            523
        );
        registryMap.emplace("minecraft:iron_chestplate",
            524
        );
        registryMap.emplace("minecraft:iron_leggings",
            525
        );
        registryMap.emplace("minecraft:iron_boots",
            526
        );
        registryMap.emplace("minecraft:diamond_helmet",
            527
        );
        registryMap.emplace("minecraft:diamond_chestplate",
            528
        );
        registryMap.emplace("minecraft:diamond_leggings",
            529
        );
        registryMap.emplace("minecraft:diamond_boots",
            530
        );
        registryMap.emplace("minecraft:golden_helmet",
            531
        );
        registryMap.emplace("minecraft:golden_chestplate",
            532
        );
        registryMap.emplace("minecraft:golden_leggings",
            533
        );
        registryMap.emplace("minecraft:golden_boots",
            534
        );
        registryMap.emplace("minecraft:flint",
            535
        );
        registryMap.emplace("minecraft:porkchop",
            536
        );
        registryMap.emplace("minecraft:cooked_porkchop",
            537
        );
        registryMap.emplace("minecraft:painting",
            538
        );
        registryMap.emplace("minecraft:golden_apple",
            539
        );
        registryMap.emplace("minecraft:enchanted_golden_apple",
            540
        );
        registryMap.emplace("minecraft:sign",
            541
        );
        registryMap.emplace("minecraft:bucket",
            542
        );
        registryMap.emplace("minecraft:water_bucket",
            543
        );
        registryMap.emplace("minecraft:lava_bucket",
            544
        );
        registryMap.emplace("minecraft:minecart",
            545
        );
        registryMap.emplace("minecraft:saddle",
            546
        );
        registryMap.emplace("minecraft:redstone",
            547
        );
        registryMap.emplace("minecraft:snowball",
            548
        );
        registryMap.emplace("minecraft:oak_boat",
            549
        );
        registryMap.emplace("minecraft:leather",
            550
        );
        registryMap.emplace("minecraft:milk_bucket",
            551
        );
        registryMap.emplace("minecraft:pufferfish_bucket",
            552
        );
        registryMap.emplace("minecraft:salmon_bucket",
            553
        );
        registryMap.emplace("minecraft:cod_bucket",
            554
        );
        registryMap.emplace("minecraft:tropical_fish_bucket",
            555
        );
        registryMap.emplace("minecraft:brick",
            556
        );
        registryMap.emplace("minecraft:clay_ball",
            557
        );
        registryMap.emplace("minecraft:sugar_cane",
            558
        );
        registryMap.emplace("minecraft:kelp",
            559
        );
        registryMap.emplace("minecraft:dried_kelp_block",
            560
        );
        registryMap.emplace("minecraft:paper",
            561
        );
        registryMap.emplace("minecraft:book",
            562
        );
        registryMap.emplace("minecraft:slime_ball",
            563
        );
        registryMap.emplace("minecraft:chest_minecart",
            564
        );
        registryMap.emplace("minecraft:furnace_minecart",
            565
        );
        registryMap.emplace("minecraft:egg",
            566
        );
        registryMap.emplace("minecraft:compass",
            567
        );
        registryMap.emplace("minecraft:fishing_rod",
            568
        );
        registryMap.emplace("minecraft:clock",
            569
        );
        registryMap.emplace("minecraft:glowstone_dust",
            570
        );
        registryMap.emplace("minecraft:cod",
            571
        );
        registryMap.emplace("minecraft:salmon",
            572
        );
        registryMap.emplace("minecraft:tropical_fish",
            573
        );
        registryMap.emplace("minecraft:pufferfish",
            574
        );
        registryMap.emplace("minecraft:cooked_cod",
            575
        );
        registryMap.emplace("minecraft:cooked_salmon",
            576
        );
        registryMap.emplace("minecraft:ink_sac",
            577
        );
        registryMap.emplace("minecraft:rose_red",
            578
        );
        registryMap.emplace("minecraft:cactus_green",
            579
        );
        registryMap.emplace("minecraft:cocoa_beans",
            580
        );
        registryMap.emplace("minecraft:lapis_lazuli",
            581
        );
        registryMap.emplace("minecraft:purple_dye",
            582
        );
        registryMap.emplace("minecraft:cyan_dye",
            583
        );
        registryMap.emplace("minecraft:light_gray_dye",
            584
        );
        registryMap.emplace("minecraft:gray_dye",
            585
        );
        registryMap.emplace("minecraft:pink_dye",
            586
        );
        registryMap.emplace("minecraft:lime_dye",
            587
        );
        registryMap.emplace("minecraft:dandelion_yellow",
            588
        );
        registryMap.emplace("minecraft:light_blue_dye",
            589
        );
        registryMap.emplace("minecraft:magenta_dye",
            590
        );
        registryMap.emplace("minecraft:orange_dye",
            591
        );
        registryMap.emplace("minecraft:bone_meal",
            592
        );
        registryMap.emplace("minecraft:bone",
            593
        );
        registryMap.emplace("minecraft:sugar",
            594
        );
        registryMap.emplace("minecraft:cake",
            595
        );
        registryMap.emplace("minecraft:white_bed",
            596
        );
        registryMap.emplace("minecraft:orange_bed",
            597
        );
        registryMap.emplace("minecraft:magenta_bed",
            598
        );
        registryMap.emplace("minecraft:light_blue_bed",
            599
        );
        registryMap.emplace("minecraft:yellow_bed",
            600
        );
        registryMap.emplace("minecraft:lime_bed",
            601
        );
        registryMap.emplace("minecraft:pink_bed",
            602
        );
        registryMap.emplace("minecraft:gray_bed",
            603
        );
        registryMap.emplace("minecraft:light_gray_bed",
            604
        );
        registryMap.emplace("minecraft:cyan_bed",
            605
        );
        registryMap.emplace("minecraft:purple_bed",
            606
        );
        registryMap.emplace("minecraft:blue_bed",
            607
        );
        registryMap.emplace("minecraft:brown_bed",
            608
        );
        registryMap.emplace("minecraft:green_bed",
            609
        );
        registryMap.emplace("minecraft:red_bed",
            610
        );
        registryMap.emplace("minecraft:black_bed",
            611
        );
        registryMap.emplace("minecraft:cookie",
            612
        );
        registryMap.emplace("minecraft:filled_map",
            613
        );
        registryMap.emplace("minecraft:shears",
            614
        );
        registryMap.emplace("minecraft:melon_slice",
            615
        );
        registryMap.emplace("minecraft:dried_kelp",
            616
        );
        registryMap.emplace("minecraft:pumpkin_seeds",
            617
        );
        registryMap.emplace("minecraft:melon_seeds",
            618
        );
        registryMap.emplace("minecraft:beef",
            619
        );
        registryMap.emplace("minecraft:cooked_beef",
            620
        );
        registryMap.emplace("minecraft:chicken",
            621
        );
        registryMap.emplace("minecraft:cooked_chicken",
            622
        );
        registryMap.emplace("minecraft:rotten_flesh",
            623
        );
        registryMap.emplace("minecraft:ender_pearl",
            624
        );
        registryMap.emplace("minecraft:blaze_rod",
            625
        );
        registryMap.emplace("minecraft:ghast_tear",
            626
        );
        registryMap.emplace("minecraft:gold_nugget",
            627
        );
        registryMap.emplace("minecraft:nether_wart",
            628
        );
        registryMap.emplace("minecraft:potion",
            629
        );
        registryMap.emplace("minecraft:glass_bottle",
            630
        );
        registryMap.emplace("minecraft:spider_eye",
            631
        );
        registryMap.emplace("minecraft:fermented_spider_eye",
            632
        );
        registryMap.emplace("minecraft:blaze_powder",
            633
        );
        registryMap.emplace("minecraft:magma_cream",
            634
        );
        registryMap.emplace("minecraft:brewing_stand",
            635
        );
        registryMap.emplace("minecraft:cauldron",
            636
        );
        registryMap.emplace("minecraft:ender_eye",
            637
        );
        registryMap.emplace("minecraft:glistering_melon_slice",
            638
        );
        registryMap.emplace("minecraft:bat_spawn_egg",
            639
        );
        registryMap.emplace("minecraft:blaze_spawn_egg",
            640
        );
        registryMap.emplace("minecraft:cave_spider_spawn_egg",
            641
        );
        registryMap.emplace("minecraft:chicken_spawn_egg",
            642
        );
        registryMap.emplace("minecraft:cod_spawn_egg",
            643
        );
        registryMap.emplace("minecraft:cow_spawn_egg",
            644
        );
        registryMap.emplace("minecraft:creeper_spawn_egg",
            645
        );
        registryMap.emplace("minecraft:dolphin_spawn_egg",
            646
        );
        registryMap.emplace("minecraft:donkey_spawn_egg",
            647
        );
        registryMap.emplace("minecraft:drowned_spawn_egg",
            648
        );
        registryMap.emplace("minecraft:elder_guardian_spawn_egg",
            649
        );
        registryMap.emplace("minecraft:enderman_spawn_egg",
            650
        );
        registryMap.emplace("minecraft:endermite_spawn_egg",
            651
        );
        registryMap.emplace("minecraft:evoker_spawn_egg",
            652
        );
        registryMap.emplace("minecraft:ghast_spawn_egg",
            653
        );
        registryMap.emplace("minecraft:guardian_spawn_egg",
            654
        );
        registryMap.emplace("minecraft:horse_spawn_egg",
            655
        );
        registryMap.emplace("minecraft:husk_spawn_egg",
            656
        );
        registryMap.emplace("minecraft:llama_spawn_egg",
            657
        );
        registryMap.emplace("minecraft:magma_cube_spawn_egg",
            658
        );
        registryMap.emplace("minecraft:mooshroom_spawn_egg",
            659
        );
        registryMap.emplace("minecraft:mule_spawn_egg",
            660
        );
        registryMap.emplace("minecraft:ocelot_spawn_egg",
            661
        );
        registryMap.emplace("minecraft:parrot_spawn_egg",
            662
        );
        registryMap.emplace("minecraft:phantom_spawn_egg",
            663
        );
        registryMap.emplace("minecraft:pig_spawn_egg",
            664
        );
        registryMap.emplace("minecraft:polar_bear_spawn_egg",
            665
        );
        registryMap.emplace("minecraft:pufferfish_spawn_egg",
            666
        );
        registryMap.emplace("minecraft:rabbit_spawn_egg",
            667
        );
        registryMap.emplace("minecraft:salmon_spawn_egg",
            668
        );
        registryMap.emplace("minecraft:sheep_spawn_egg",
            669
        );
        registryMap.emplace("minecraft:shulker_spawn_egg",
            670
        );
        registryMap.emplace("minecraft:silverfish_spawn_egg",
            671
        );
        registryMap.emplace("minecraft:skeleton_spawn_egg",
            672
        );
        registryMap.emplace("minecraft:skeleton_horse_spawn_egg",
            673
        );
        registryMap.emplace("minecraft:slime_spawn_egg",
            674
        );
        registryMap.emplace("minecraft:spider_spawn_egg",
            675
        );
        registryMap.emplace("minecraft:squid_spawn_egg",
            676
        );
        registryMap.emplace("minecraft:stray_spawn_egg",
            677
        );
        registryMap.emplace("minecraft:tropical_fish_spawn_egg",
            678
        );
        registryMap.emplace("minecraft:turtle_spawn_egg",
            679
        );
        registryMap.emplace("minecraft:vex_spawn_egg",
            680
        );
        registryMap.emplace("minecraft:villager_spawn_egg",
            681
        );
        registryMap.emplace("minecraft:vindicator_spawn_egg",
            682
        );
        registryMap.emplace("minecraft:witch_spawn_egg",
            683
        );
        registryMap.emplace("minecraft:wither_skeleton_spawn_egg",
            684
        );
        registryMap.emplace("minecraft:wolf_spawn_egg",
            685
        );
        registryMap.emplace("minecraft:zombie_spawn_egg",
            686
        );
        registryMap.emplace("minecraft:zombie_horse_spawn_egg",
            687
        );
        registryMap.emplace("minecraft:zombie_pigman_spawn_egg",
            688
        );
        registryMap.emplace("minecraft:zombie_villager_spawn_egg",
            689
        );
        registryMap.emplace("minecraft:experience_bottle",
            690
        );
        registryMap.emplace("minecraft:fire_charge",
            691
        );
        registryMap.emplace("minecraft:writable_book",
            692
        );
        registryMap.emplace("minecraft:written_book",
            693
        );
        registryMap.emplace("minecraft:emerald",
            694
        );
        registryMap.emplace("minecraft:item_frame",
            695
        );
        registryMap.emplace("minecraft:flower_pot",
            696
        );
        registryMap.emplace("minecraft:carrot",
            697
        );
        registryMap.emplace("minecraft:potato",
            698
        );
        registryMap.emplace("minecraft:baked_potato",
            699
        );
        registryMap.emplace("minecraft:poisonous_potato",
            700
        );
        registryMap.emplace("minecraft:map",
            701
        );
        registryMap.emplace("minecraft:golden_carrot",
            702
        );
        registryMap.emplace("minecraft:skeleton_skull",
            703
        );
        registryMap.emplace("minecraft:wither_skeleton_skull",
            704
        );
        registryMap.emplace("minecraft:player_head",
            705
        );
        registryMap.emplace("minecraft:zombie_head",
            706
        );
        registryMap.emplace("minecraft:creeper_head",
            707
        );
        registryMap.emplace("minecraft:dragon_head",
            708
        );
        registryMap.emplace("minecraft:carrot_on_a_stick",
            709
        );
        registryMap.emplace("minecraft:nether_star",
            710
        );
        registryMap.emplace("minecraft:pumpkin_pie",
            711
        );
        registryMap.emplace("minecraft:firework_rocket",
            712
        );
        registryMap.emplace("minecraft:firework_star",
            713
        );
        registryMap.emplace("minecraft:enchanted_book",
            714
        );
        registryMap.emplace("minecraft:nether_brick",
            715
        );
        registryMap.emplace("minecraft:quartz",
            716
        );
        registryMap.emplace("minecraft:tnt_minecart",
            717
        );
        registryMap.emplace("minecraft:hopper_minecart",
            718
        );
        registryMap.emplace("minecraft:prismarine_shard",
            719
        );
        registryMap.emplace("minecraft:prismarine_crystals",
            720
        );
        registryMap.emplace("minecraft:rabbit",
            721
        );
        registryMap.emplace("minecraft:cooked_rabbit",
            722
        );
        registryMap.emplace("minecraft:rabbit_stew",
            723
        );
        registryMap.emplace("minecraft:rabbit_foot",
            724
        );
        registryMap.emplace("minecraft:rabbit_hide",
            725
        );
        registryMap.emplace("minecraft:armor_stand",
            726
        );
        registryMap.emplace("minecraft:iron_horse_armor",
            727
        );
        registryMap.emplace("minecraft:golden_horse_armor",
            728
        );
        registryMap.emplace("minecraft:diamond_horse_armor",
            729
        );
        registryMap.emplace("minecraft:lead",
            730
        );
        registryMap.emplace("minecraft:name_tag",
            731
        );
        registryMap.emplace("minecraft:command_block_minecart",
            732
        );
        registryMap.emplace("minecraft:mutton",
            733
        );
        registryMap.emplace("minecraft:cooked_mutton",
            734
        );
        registryMap.emplace("minecraft:white_banner",
            735
        );
        registryMap.emplace("minecraft:orange_banner",
            736
        );
        registryMap.emplace("minecraft:magenta_banner",
            737
        );
        registryMap.emplace("minecraft:light_blue_banner",
            738
        );
        registryMap.emplace("minecraft:yellow_banner",
            739
        );
        registryMap.emplace("minecraft:lime_banner",
            740
        );
        registryMap.emplace("minecraft:pink_banner",
            741
        );
        registryMap.emplace("minecraft:gray_banner",
            742
        );
        registryMap.emplace("minecraft:light_gray_banner",
            743
        );
        registryMap.emplace("minecraft:cyan_banner",
            744
        );
        registryMap.emplace("minecraft:purple_banner",
            745
        );
        registryMap.emplace("minecraft:blue_banner",
            746
        );
        registryMap.emplace("minecraft:brown_banner",
            747
        );
        registryMap.emplace("minecraft:green_banner",
            748
        );
        registryMap.emplace("minecraft:red_banner",
            749
        );
        registryMap.emplace("minecraft:black_banner",
            750
        );
        registryMap.emplace("minecraft:end_crystal",
            751
        );
        registryMap.emplace("minecraft:chorus_fruit",
            752
        );
        registryMap.emplace("minecraft:popped_chorus_fruit",
            753
        );
        registryMap.emplace("minecraft:beetroot",
            754
        );
        registryMap.emplace("minecraft:beetroot_seeds",
            755
        );
        registryMap.emplace("minecraft:beetroot_soup",
            756
        );
        registryMap.emplace("minecraft:dragon_breath",
            757
        );
        registryMap.emplace("minecraft:splash_potion",
            758
        );
        registryMap.emplace("minecraft:spectral_arrow",
            759
        );
        registryMap.emplace("minecraft:tipped_arrow",
            760
        );
        registryMap.emplace("minecraft:lingering_potion",
            761
        );
        registryMap.emplace("minecraft:shield",
            762
        );
        registryMap.emplace("minecraft:elytra",
            763
        );
        registryMap.emplace("minecraft:spruce_boat",
            764
        );
        registryMap.emplace("minecraft:birch_boat",
            765
        );
        registryMap.emplace("minecraft:jungle_boat",
            766
        );
        registryMap.emplace("minecraft:acacia_boat",
            767
        );
        registryMap.emplace("minecraft:dark_oak_boat",
            768
        );
        registryMap.emplace("minecraft:totem_of_undying",
            769
        );
        registryMap.emplace("minecraft:shulker_shell",
            770
        );
        registryMap.emplace("minecraft:iron_nugget",
            771
        );
        registryMap.emplace("minecraft:knowledge_book",
            772
        );
        registryMap.emplace("minecraft:debug_stick",
            773
        );
        registryMap.emplace("minecraft:music_disc_13",
            774
        );
        registryMap.emplace("minecraft:music_disc_cat",
            775
        );
        registryMap.emplace("minecraft:music_disc_blocks",
            776
        );
        registryMap.emplace("minecraft:music_disc_chirp",
            777
        );
        registryMap.emplace("minecraft:music_disc_far",
            778
        );
        registryMap.emplace("minecraft:music_disc_mall",
            779
        );
        registryMap.emplace("minecraft:music_disc_mellohi",
            780
        );
        registryMap.emplace("minecraft:music_disc_stal",
            781
        );
        registryMap.emplace("minecraft:music_disc_strad",
            782
        );
        registryMap.emplace("minecraft:music_disc_ward",
            783
        );
        registryMap.emplace("minecraft:music_disc_11",
            784
        );
        registryMap.emplace("minecraft:music_disc_wait",
            785
        );
        registryMap.emplace("minecraft:trident",
            786
        );
        registryMap.emplace("minecraft:phantom_membrane",
            787
        );
        registryMap.emplace("minecraft:nautilus_shell",
            788
        );
        registryMap.emplace("minecraft:heart_of_the_sea",
            789
        );
        reverseMap = inverse_map(registryMap);
	}

	ItemProtocolID ItemRegistry::getIDByName(std::string namespaceid)
	{
		return registryMap[namespaceid];
	}

	std::string ItemRegistry::getNameByID(ItemProtocolID protocolid)
	{
		return reverseMap[protocolid];
	}

	ItemRegistry* g_ItemRegistry;
}