//All 1.15.2+ gamerules
pub const GameRules = struct{
    announceAdvancements: bool,
    commandBlockOutput: bool,
    disableElytraMovementCheck: bool,
    disableRaids: bool,
    doDaylightCycle: bool,
    doEntityDrops: bool,
    doFireTick: bool,
    doInsomnia: bool,
    doImmediateRespawn: bool,
    doLimitedCrafting: bool,
    doMobLoot: bool,
    doMobSpawning: bool,
    doPatrolSpawning: bool,
    doTileDrops: bool,
    doTraderSpawning: bool,
    doWeatherCycle: bool,
    drowningDamage: bool,
    fallDamage: bool,
    fireDamage: bool,
    forgiveDeadPlayers: bool,
    keepInventory: bool,
    logAdminCommands: bool,
    maxCommandChainLength: u16,
    maxEntityCramming: u8,
    mobGriefing: bool,
    naturalRegeneration: bool,
    randomTickSpeed: u16,
    reducedDebugInfo: bool,
    sendCommandFeedback: bool,
    showCoordinates: bool,
    showDeathMessages: bool,
    spawnRadius: u16,
    spectatorsGenerateChunks: bool,
    tntExplodes: bool,
    universalAnger: bool,
};

