pub const GameRules = struct{
    announceAdvancements: bool,
    commandBlockOutput: bool,
    disableElytraMovementCheck: bool,
    disableRaids: bool,
    doDaylightCycle: bool,
    doEntityDrops: bool,
    doFireTick: bool,
    doInsomnia: bool,
    doImmediateRespawn: bool,
    doLimitedCrafting: bool,
    doMobLoot: bool,
    doMobSpawning: bool,
    doPatrolSpawning: bool,
    doTileDrops: bool,
    doTraderSpawning: bool,
    doWeatherCycle: bool,
    drowningDamage: bool,
    fallDamage: bool,
    fireDamage: bool,
    forgiveDeadPlayers: bool,
    keepInventory: bool,
    logAdminCommands: bool,
    maxCommandChainLength: u16,
    maxEntityCramming: u8,
    mobGriefing: bool,
    naturalRegeneration: bool,
    randomTickSpeed: u16,
    reducedDebugInfo: bool,
    sendCommandFeedback: bool,
    showCoordinates: bool,
    showDeathMessages: bool,
    spawnRadius: u16,
    spectatorsGenerateChunks: bool,
    tntExplodes: bool,
    universalAnger: bool,
};

pub const rules = GameRules{
    .announceAdvancements = true,
    .commandBlockOutput = true, 
    .disableElytraMovementCheck = false,
    .disableRaids = false,
    .doDaylightCycle = true,
    .doEntityDrops = true,
    .doFireTick = true,
    .doInsomnia = true,
    .doImmediateRespawn = false,
    .doLimitedCrafting = false,
    .doMobLoot = true,
    .doMobSpawning = true,
    .doPatrolSpawning = true,
    .doTileDrops = true,
    .doTraderSpawning = true,
    .doWeatherCycle = true,
    .drowningDamage = true,
    .fallDamage = true,
    .fireDamage = true,
    .forgiveDeadPlayers = true,
    .keepInventory = false,
    .logAdminCommands = true,
    .maxCommandChainLength = 65536,
    .maxEntityCramming = 24,
    .mobGriefing = true,
    .naturalRegeneration = true,
    .randomTickSpeed = 3,
    .reducedDebugInfo = false,
    .sendCommandFeedback = true,
    .showCoordinates = true,
    .showDeathMessages = true,
    .spawnRadius = 10,
    .spectatorsGenerateChunks = true,
    .tntExplodes = true,
    .universalAnger = false
};
